CREATE TABLE OdysseyPTBPRD.AccChargeCode (
	AC_PK CHAR(MAX)  ,
	AC_Code varchar(20)  ,
	AC_IsActive VARCHAR(10) ,
	AC_Desc varchar(200)  ,
	AC_LocalLanguageDescription nvarchar(80)  ,
	AC_ChargeType char(3)  ,
	AC_GoodsServiceType varchar(3)  ,
	AC_MarginPercentage decimal(5,2) ,
	AC_InputGSTVATRecoverable decimal(5,4) ,
	AC_AW_WithholdingTaxRate CHAR(MAX) ,
	AC_AT_GSTRate CHAR(MAX) ,
	AC_AG_RevenueAccount CHAR(MAX) ,
	AC_AG_WIPAccount CHAR(MAX) ,
	AC_AG_CostAccount CHAR(MAX) ,
	AC_AG_AccrualAccount CHAR(MAX) ,
	AC_PrintSequence smallint ,
	AC_AR_SalesGroup CHAR(MAX) ,
	AC_AR_ExpenseGroup CHAR(MAX) ,
	AC_ChargeGroup varchar(3)  ,
	AC_ChargeSubGroup varchar(3)  ,
	AC_ChargeOtherGroups varchar(3)  ,
	AC_IsGroupageCharge varchar(10) ,
	AC_RateCalculator varchar(3)  ,
	AC_ShowOnQuotation VARCHAR(10) ,
	AC_SuppressOnQuoteIfZero VARCHAR(10) ,
	AC_DepartmentFilterList varchar(200)  ,
	AC_AllowDescriptionOvertype VARCHAR(10) ,
	AC_IsCommissionable VARCHAR(10) ,
	AC_IATA_ChargeCodeMap varchar(2)  ,
	AC_eNettChargeCodeMap varchar(10)  ,
	AC_AX_TaxOverrideGroup CHAR(MAX) ,
	AC_GC CHAR(MAX) ,
	AC_EnergySourceGroup varchar(3)  ,
	AC_DefaultCommissionProduct varchar(8)  ,
	AC_DefaultCommissionService varchar(8)  ,
	AC_DefaultCommissionSubModule varchar(8)  ,
	AC_AC_RevenueChargeCode CHAR(MAX) ,
	AC_GovtChargeCode nvarchar(20)  ,
	AC_IsAdhocServiceCharge VARCHAR(10) ,
	AC_UniversalChargeCodeMap varchar(10), 
    __ts_ms BIGINT DEFAULT NULL,
    __deleted varchar(20) DEFAULT NULL
)


CREATE TABLE OdysseyPTBPRD.AccGLAggregate (
	AA_PK CHAR(MAX) ,
	AA_Amount DECIMAL(15,4) ,
	AA_TransactionCategory varchar(3)  ,
	AA_Period int ,
	AA_AG CHAR(MAX) ,
	AA_GB CHAR(MAX) ,
	AA_GE CHAR(MAX) ,
	AA_GC CHAR(MAX) 
)

CREATE TABLE OdysseyPTBPRD.AccGLHeader (
	AG_PK CHAR(MAX) ,
	AG_AccountGroup varchar(20)  ,
	AG_AccountNum varchar(10)  ,
	AG_IsActive VARCHAR(10) ,
	AG_Description varchar(35)  ,
	AG_AccountType char(3)  ,
	AG_CashFlowType varchar(3)  ,
	AG_DeVARCHAR(10)Credit char(2)  ,
	AG_IsGlobal VARCHAR(10) ,
	AG_ControlAccount VARCHAR(10) ,
	AG_DisallowDirectPosting VARCHAR(10) ,
	AG_AG_AlternateNum CHAR(MAX) ,
	AG_AG_PercentNum CHAR(MAX) ,
	AG_AG_ConsolidationNum CHAR(MAX) ,
	AG_AG_HeaderDependsOnTotal CHAR(MAX) ,
	AG_TotalLevel int ,
	AG_Column char(2)  ,
	AG_PrintSequence int ,
	AG_IsSubClassValidationRuleMandatory VARCHAR(10) ,
	AG_SubClass varchar(3)  ,
	AG_Notes nvarchar(MAX)
	)


CREATE TABLE OdysseyPTBPRD.AccGroups (
	AR_PK CHAR(MAX) ,
	AR_Code varchar(10)  ,
	AR_Desc varchar(35)
)

CREATE TABLE OdysseyPTBPRD.AccTransactionHeader (
	AH_PK CHAR(MAX) ,
	AH_Ledger char(2)  ,
	AH_TransactionType char(3)  ,
	AH_ComplianceSubType char(3)  ,
	AH_TransactionNum varchar(38)  ,
	AH_TransactionCount VARCHAR(10) ,
	AH_TransactionReference varchar(20)  ,
	AH_Desc nvarchar(128)  ,
	AH_InvoiceDate TIMESTAMP ,
	AH_DueDate TIMESTAMP ,
	AH_InvoiceAmount DECIMAL(30,4) ,
	AH_GSTAmount DECIMAL(30,4) ,
	AH_WithholdingTax DECIMAL(30,4) ,
	AH_OSTotal DECIMAL(30,4) ,
	AH_RX_NKTransactionCurrency varchar(3)  ,
	AH_ExchangeRate decimal(30,9) ,
	AH_AgePeriod int ,
	AH_PostPeriod int ,
	AH_PostDate TIMESTAMP ,
	AH_TransactionCategory varchar(3)  ,
	AH_ChequeOrReference varchar(38)  ,
	AH_ReceiptType char(3)  ,
	AH_CashBasisGSTIndicator VARCHAR(10) ,
	AH_CashBasisGSTRealisedToGL VARCHAR(10) ,
	AH_ChequeDrawer nvarchar(50)  ,
	AH_DrawerBank nvarchar(25)  ,
	AH_DrawerBranch nvarchar(25)  ,
	AH_InvoiceApproved VARCHAR(10) ,
	AH_ConsolidatedInvoiceRef varchar(38)  ,
	AH_FullyPaidDate TIMESTAMP ,
	AH_InvoicePrinted VARCHAR(10) ,
	AH_IsCancelled VARCHAR(10) ,
	AH_DateClearedInCashbook TIMESTAMP ,
	AH_NotAllocated VARCHAR(10) ,
	AH_OutstandingAmount DECIMAL(30,4) ,
	AH_PostedToEFT VARCHAR(10) ,
	AH_PostToGL varchar(1)  ,
	AH_ReceiptBatchNo varchar(20)  ,
	AH_TransactionCreatedByMatching VARCHAR(10) ,
	AH_InvoiceTerm char(3)  ,
	AH_InvoiceTermDays VARCHAR(10) ,
	AH_RequisitionDate TIMESTAMP ,
	AH_RequisitionStatus varchar(3)  ,
	AH_NumberOfSupportingDocuments VARCHAR(10) ,
	AH_ExportBatchNumber int ,
	AH_PostedInternal VARCHAR(10) ,
	AH_POST1 VARCHAR(10) ,
	AH_POST2 VARCHAR(10) ,
	AH_POST3 VARCHAR(10) ,
	AH_POST4 VARCHAR(10) ,
	AH_AB CHAR(MAX) ,
	AH_OH CHAR(MAX) ,
	AH_OA_InvoiceAddressOverride CHAR(MAX) ,
	AH_OC_InvoiceContactOverride CHAR(MAX) ,
	AH_JH CHAR(MAX) ,
	AH_GB CHAR(MAX) ,
	AH_GC CHAR(MAX) ,
	AH_GE CHAR(MAX) ,
	AH_AG CHAR(MAX) ,
	AH_TransactionBelongsToGroup CHAR(MAX) ,
	AH_AH_InvoiceStatement CHAR(MAX) ,
	AH_SubClassParentTableCode varchar(3)  ,
	AH_SubClassParentId CHAR(MAX) ,
	AH_SystemCreateTimeUtc TIMESTAMP ,
	AH_SystemCreateUser varchar(3)  ,
	AH_SystemLastEditTimeUtc TIMESTAMP ,
	AH_SystemLastEditUser varchar(3)  ,
	AH_AgreedPaymentMethodOverride varchar(3)  ,
	AH_ComplianceDocumentDate date ,
	AH_GS_NKAuditedBy varchar(3)  ,
	AH_GS_NKCashier varchar(3)  ,
	AH_InvoicePaymentReferenceCode varchar(3)  ,
	AH_DigitalSignature_COMPRESSED VARCHAR(MAX) ,
	AH_LocalTaxAmountOtherTaxes DECIMAL(30,4) ,
	AH_OSTaxAmountOtherTaxes DECIMAL(30,4) ,
	AH_PlaceOfSupply varchar(5)  ,
	AH_PlaceOfSupplyType varchar(3) 
)


CREATE TABLE OdysseyPTBPRD.AccTransactionLines (
	AL_PK CHAR(MAX) ,
	AL_LineType char(3)  ,
	AL_Sequence VARCHAR(20) ,
	AL_Desc nvarchar(1024)  ,
	AL_LineAmount DECIMAL(15,4) ,
	AL_AT CHAR(MAX) ,
	AL_GSTVAT DECIMAL(15,4) ,
	AL_GSTVATBasis char(5)  ,
	AL_A9_VATClass CHAR(MAX) ,
	AL_AW CHAR(MAX) ,
	AL_WithholdingTax DECIMAL(15,4) ,
	AL_UnitQty int ,
	AL_UnitPrice DECIMAL(15,4) ,
	AL_OSUnitPrice DECIMAL(15,4) ,
	AL_OSAmount DECIMAL(15,4) ,
	AL_RX_NKTransactionCurrency varchar(3)  ,
	AL_ExchangeRate decimal(18,9) ,
	AL_InputGSTVATRecoverable decimal(5,4) ,
	AL_PostPeriod int ,
	AL_PostDate TIMESTAMP ,
	AL_PostToGL varchar(1)  ,
	AL_ReversePeriod int ,
	AL_ReverseDate TIMESTAMP ,
	AL_ReverseToGL varchar(1)  ,
	AL_PreventInvoicePrintGrouping VARCHAR(20) ,
	AL_ExportBatchNumber int ,
	AL_ExportReverseBatchNumber int ,
	AL_IsFinalCharge VARCHAR(20) ,
	AL_RevRecognitionType varchar(3)  ,
	AL_JH CHAR(MAX) ,
	AL_AC CHAR(MAX) ,
	AL_GE CHAR(MAX) ,
	AL_GB CHAR(MAX) ,
	AL_AG CHAR(MAX) ,
	AL_OH CHAR(MAX) ,
	AL_AG_PercentOf CHAR(MAX) ,
	AL_PercentageOfPeriod int ,
	AL_AH CHAR(MAX) ,
	AL_GC CHAR(MAX) ,
	AL_SubClassParentTableCode varchar(3)  ,
	AL_SubClassParentId CHAR(MAX) ,
	AL_SystemCreateTimeUtc TIMESTAMP ,
	AL_SystemCreateUser varchar(3)  ,
	AL_SystemLastEditTimeUtc TIMESTAMP ,
	AL_SystemLastEditUser varchar(3)  ,
	AL_GovtChargeCode nvarchar(20)  ,
	AL_GSTVATExtra DECIMAL(15,4) ,
	AL_TaxDate date ,
	AL_TaxExtraRateDenominator int ,
	AL_TaxExtraRateNumerator int ,
	AL_TaxRateDenominator int ,
	AL_TaxRateNumerator int ,
	AL_PlaceOfSupply varchar(5)  ,
	AL_PlaceOfSupplyType varchar(3)
)



CREATE TABLE OdysseyPTBPRD.AccTransactionMatchLink (
	AP_PK CHAR(MAX) ,
	AP_Amount DECIMAL(15,4) ,
	AP_GSTRealised DECIMAL(15,4) ,
	AP_MatchGroupNum varchar(20)  ,
	AP_MatchPeriod int ,
	AP_MatchDate TIMESTAMP ,
	AP_AH CHAR(MAX) ,
	AP_Reason varchar(3) 
)

CREATE TABLE OdysseyPTBPRD.DtbBooking (
	KM_PK CHAR(MAX) ,
	KM_JobID varchar(20)  ,
	KM_KT_NKBookingTemplate varchar(4)  ,
	KM_IsActive VARCHAR(20) ,
	KM_RequiresRefrigeration VARCHAR(20) ,
	KM_IsHazardous VARCHAR(20) ,
	KM_Status varchar(3)  ,
	KM_Description varchar(80)  ,
	KM_Direction varchar(3)  ,
	KM_TransportReference varchar(35)  ,
	KM_KB_Booking CHAR(MAX) ,
	KM_KB_BookingConsolidationMultiJob CHAR(MAX) ,
	KM_Chargeable decimal(9,3) ,
	KM_OverrideChargeable VARCHAR(20) ,
	KM_RS_NKServiceLevel varchar(3)  ,
	KM_PL_NKCarrierServiceLevel varchar(3)  ,
	KM_RatingFreightMode varchar(3)  ,
	KM_SystemCreateTimeUtc TIMESTAMP ,
	KM_SystemCreateUser varchar(3)  ,
	KM_SystemLastEditTimeUtc TIMESTAMP ,
	KM_SystemLastEditUser varchar(3)  ,
	KM_GB_Branch CHAR(MAX) ,
	KM_Distance decimal(9,3) ,
	KM_DistanceUnit char(2)  ,
	KM_JobType char(3)  ,
	KM_OAN_CarrierAccount CHAR(MAX) ,
	KM_BookingOfTransportRequestedDate TIMESTAMP
)








CREATE TABLE OdysseyPTBPRD.DtbBookingConfirmation (
	KK_PK CHAR(MAX) ,
	KK_ConfirmationType varchar(3)  ,
	KK_Estimated TIMESTAMP ,
	KK_EstimatedUtc TIMESTAMP ,
	KK_Actual TIMESTAMP ,
	KK_RequiredFrom TIMESTAMP ,
	KK_RequiredFromUtc TIMESTAMP ,
	KK_RequiredTo TIMESTAMP ,
	KK_RequiredToUtc TIMESTAMP ,
	KK_ReferenceNum varchar(20)  ,
	KK_Quantity int ,
	KK_ReceivedBySignature VARCHAR(MAX) ,
	KK_IsEmptyContainer VARCHAR(10) ,
	KK_KN_BookingInstruction CHAR(MAX) ,
	KK_KD_BookingInstructionPkgDivot CHAR(MAX) ,
	KK_K1_RunSheetInstruction CHAR(MAX) ,
	KK_ReceivedBy nvarchar(50)  ,
	KK_SlotDateTime TIMESTAMP ,
	KK_SlotReference varchar(20) 
)


CREATE TABLE OdysseyPTBPRD.DtbBookingConsolidation (
	KB_PK CHAR(MAX) ,
	KB_JobID varchar(15)  ,
	KB_JobDirection varchar(3)  ,
	KB_GoodsDescription varchar(128)  ,
	KB_Status varchar(3)  ,
	KB_IsMultiJob VARCHAR(10) ,
	KB_IsOverridden VARCHAR(10) ,
	KB_ParentID CHAR(MAX) ,
	KB_ParentTableCode varchar(3)  ,
	KB_JobType char(3) 
)

==========================================================================================================


CREATE TABLE OdysseyPTBPRD.DtbBookingInstruction (
	KN_PK CHAR(MAX) ,
	KN_Sequence int ,
	KN_InstructionType varchar(3)  ,
	KN_DropMode varchar(3)  ,
	KN_ServiceInstruction nvarchar(MAX)  ,
	KN_Status varchar(3)  ,
	KN_RQ_Equipment CHAR(MAX) ,
	KN_KM_BookingMovement CHAR(MAX) ,
	KN_IsContainerRateable VARCHAR(10) ,
	KN_IsLooseRateable VARCHAR(10) ,
	KN_TZ_DomesticZone CHAR(MAX) ,
	KN_IsAuthorisedToLeave VARCHAR(10) 
)


CREATE TABLE OdysseyPTBPRD.DtbConsignmentRunSheetInstruction (
	K1_PK CHAR(MAX) ,
	K1_KG_RunSheet CHAR(MAX) ,
	K1_Sequence int ,
	K1_TimeIn TIMESTAMP ,
	K1_TimeOut TIMESTAMP ,
	K1_IsAcceptedByDriver VARCHAR(10) ,
	K1_EstimatedTimeIn TIMESTAMP ,
	K1_EstimatedTimeOut TIMESTAMP ,
	K1_FailureNotes varchar(MAX)  ,
	K1_FailureReason varchar(3)  ,
	K1_InstructionType varchar(3)  ,
	K1_ReceivedBy nvarchar(50)  ,
	K1_ReceivedBySignature VARCHAR(MAX) ,
	K1_RegisteredPalletSpaces int ,
	K1_RegisteredVolume decimal(9,3) ,
	K1_RegisteredVolumeUQ varchar(2)  ,
	K1_RegisteredWeight decimal(9,3) ,
	K1_RegisteredWeightUQ varchar(2)  


CREATE TABLE OdysseyPTBPRD.GenCustomAddOnValue (
	XV_PK CHAR(MAX) ,
	XV_Name varchar(32)  ,
	XV_Type varchar(3)  ,
	XV_Data nvarchar(100)  ,
	XV_IsRuleEnabled VARCHAR(10) ,
	XV_XR_Rule CHAR(MAX) ,
	XV_ParentTableCode varchar(3)  ,
	XV_ParentID CHAR(MAX) 
)

CREATE TABLE OdysseyPTBPRD.GlbBranch (
	GB_PK CHAR(MAX) ,
	GB_IsValid VARCHAR(10) ,
	GB_Code char(3)  ,
	GB_IsActive VARCHAR(10) ,
	GB_BranchName nvarchar(50)  ,
	GB_Address1 nvarchar(50)  ,
	GB_Address2 nvarchar(50)  ,
	GB_City nvarchar(25)  ,
	GB_State nvarchar(25)  ,
	GB_PostCode varchar(10)  ,
	GB_Phone varchar(20)  ,
	GB_Fax varchar(20)  ,
	GB_InternalExtension varchar(20)  ,
	GB_Email nvarchar(254)  ,
	GB_WebAddress varchar(60)  ,
	GB_RL_NKHomePort varchar(5)  ,
	GB_LocalDocLanguage varchar(3)  ,
	GB_OH_OrgProxy CHAR(MAX) ,
	GB_GC CHAR(MAX) ,
	GB_AccountingGroupCode varchar(3)  ,
	GB_OA_AddressProxy CHAR(MAX) ,
	GB_RN_NKCountryCode varchar(2)  ,
	GB_AddressMap varchar(50)  ,
	GB_GeoLocation GEOMETRY ,
	GB_ValidationStatus char(3)
)

CREATE TABLE OdysseyPTBPRD.GlbCompany (
	GC_PK CHAR(MAX) ,
	GC_IsValid VARCHAR(10) ,
	GC_Code char(3)  ,
	GC_IsActive VARCHAR(10) ,
	GC_Name nvarchar(100)  ,
	GC_BusinessRegNo nvarchar(35)  ,
	GC_BusinessRegNo2 nvarchar(35)  ,
	GC_CustomsRegistrationNo nvarchar(35)  ,
	GC_Address1 nvarchar(50)  ,
	GC_Address2 nvarchar(50)  ,
	GC_City nvarchar(25)  ,
	GC_Phone varchar(20)  ,
	GC_PostCode varchar(10)  ,
	GC_State nvarchar(25)  ,
	GC_Fax varchar(20)  ,
	GC_Email nvarchar(254)  ,
	GC_WebAddress varchar(250)  ,
	GC_ExRateDisplayMode varchar(3)  ,
	GC_ExRateDecimals VARCHAR(10) ,
	GC_IsGSTRegistered VARCHAR(10) ,
	GC_IsGSTCashBasis VARCHAR(10) ,
	GC_IsWHTRegistered VARCHAR(10) ,
	GC_IsWHTCashBasis VARCHAR(10) ,
	GC_NoOfAccountingPeriods int ,
	GC_PeriodFormat char(3)  ,
	GC_StartDate TIMESTAMP ,
	GC_PeriodEndWeekDay char(3)  ,
	GC_GLCurrentPeriod int ,
	GC_ARAPCurrentPeriod int ,
	GC_GLClosedPeriod int ,
	GC_ARAPClosedPeriod int ,
	GC_RX_NKLocalCurrency varchar(3)  ,
	GC_RN_NKCountryCode varchar(2)  ,
	GC_IsReciprocal VARCHAR(10) ,
	GC_LocalDocLanguage varchar(3)  ,
	GC_OH_OrgProxy CHAR(MAX) ,
	GC_AddressMap varchar(50)  ,
	GC_GeoLocation GEOMETRY ,
	GC_ValidationStatus char(3)
)

CREATE TABLE OdysseyPTBPRD.GlbDepartment (
	GE_PK CHAR(MAX) ,
	GE_IsValid VARCHAR(10) ,
	GE_Code char(3)  ,
	GE_IsActive VARCHAR(10) ,
	GE_Desc varchar(35)  ,
	GE_SystemCode VARCHAR(10) ,
	GE_Air VARCHAR(10) ,
	GE_Sea VARCHAR(10) ,
	GE_Road VARCHAR(10) ,
	GE_Rail VARCHAR(10) ,
	GE_Post VARCHAR(10) ,
	GE_NonTransport VARCHAR(10) ,
	GE_Export VARCHAR(10) ,
	GE_Import VARCHAR(10) ,
	GE_Domestic VARCHAR(10) ,
	GE_NonDirectional VARCHAR(10) ,
	GE_InternationalFreight VARCHAR(10) ,
	GE_CustomsBrokerage VARCHAR(10) ,
	GE_LocalTransport VARCHAR(10) ,
	GE_LineHaul VARCHAR(10) ,
	GE_DepotCFS VARCHAR(10) ,
	GE_Warehouse VARCHAR(10) ,
	GE_Misc VARCHAR(10) ,
	GE_GE CHAR(MAX) 
    )

CREATE TABLE OdysseyPTBPRD.GlbStaff (
	GS_PK CHAR(MAX) ,
	GS_Password varchar(128)  ,
	GS_IsOperational VARCHAR(10) ,
	GS_ChangePasswordAtNextLogin VARCHAR(10) ,
	GS_IsActive VARCHAR(10) ,
	GS_IsController VARCHAR(10) ,
	GS_IsSystemAccount VARCHAR(10) ,
	GS_Code varchar(3)  ,
	GS_LoginName nvarchar(104)  ,
	GS_IsValid VARCHAR(10) ,
	GS_IsResource VARCHAR(10) ,
	GS_ResourceType varchar(3)  ,
	GS_IsSalesRep VARCHAR(10) ,
	GS_IsDatabaseDeveloper VARCHAR(10) ,
	GS_IsDeveloper VARCHAR(10) ,
	GS_IsBackupOperator VARCHAR(10) ,
	GS_IsReadOnlyDBUser VARCHAR(10) ,
	GS_EmploymentBasis varchar(3)  ,
	GS_NameTitle nvarchar(10)  ,
	GS_FullName nvarchar(256)  ,
	GS_NameSuffix nvarchar(10)  ,
	GS_FriendlyName nvarchar(80)  ,
	GS_UserAddress1 nvarchar(1024)  ,
	GS_UserAddress2 nvarchar(50)  ,
	GS_City nvarchar(128)  ,
	GS_State nvarchar(128)  ,
	GS_Postcode nvarchar(40)  ,
	GS_Gender varchar(1)  ,
	GS_Title nvarchar(128)  ,
	GS_WorkPhone varchar(20)  ,
	GS_PublishWorkPhone VARCHAR(10) ,
	GS_WorkExtension varchar(10)  ,
	GS_PublishWorkExtension VARCHAR(10) ,
	GS_HomePhone varchar(20)  ,
	GS_PublishHomePhone VARCHAR(10) ,
	GS_MobilePhone varchar(20)  ,
	GS_PublishMobilePhone VARCHAR(10) ,
	GS_FaxNum varchar(20)  ,
	GS_PublishFaxNum VARCHAR(10) ,
	GS_Pager varchar(20)  ,
	GS_SecurityCardNumber varchar(20)  ,
	GS_EnterpriseCertificationID varchar(20)  ,
	GS_EmailAddress nvarchar(254)  ,
	GS_PublishEmailAddress VARCHAR(10) ,
	GS_Birthdate date ,
	GS_EftWages VARCHAR(10) ,
	GS_WagesBankName nvarchar(35)  ,
	GS_WagesBankAccount varchar(35)  ,
	GS_WagesBankBsb varchar(15)  ,
	GS_WagesBankSwift varchar(35)  ,
	GS_NextOfKinRelationship varchar(3)  ,
	GS_NextOfKin nvarchar(50)  ,
	GS_NextOfKinHomePhone varchar(20)  ,
	GS_NextOfKinWorkPhone varchar(20)  ,
	GS_EmergencyContactRelationship varchar(3)  ,
	GS_EmergencyContactName nvarchar(50)  ,
	GS_EmergencyHomePhone varchar(20)  ,
	GS_EmergencyWorkPhone varchar(20)  ,
	GS_EmploymentDate TIMESTAMP ,
	GS_DepartureDate TIMESTAMP ,
	GS_UserSignature VARCHAR(MAX) ,
	GS_ProfilePhoto VARCHAR(MAX) ,
	GS_DueBack TIMESTAMP ,
	GS_OutOnTask varchar(50)  ,
	GS_PersonalEDIMailBox varchar(20)  ,
	GS_BrokerID varchar(20)  ,
	GS_BrokerPassword varchar(128)  ,
	GS_BrokerWorkingPassword varchar(128)  ,
	GS_BrokerPasswordStatus varchar(3)  ,
	GS_Passport varchar(20)  ,
	GS_IsInTrainingMode VARCHAR(10) ,
	GS_PasswordReuseScratch varchar(1024)  ,
	GS_LastPasswordChangeDate TIMESTAMP ,
	GS_LastPasswordAttemptDateTime_UTC TIMESTAMP ,
	GS_LockoutDateTime_UTC TIMESTAMP ,
	GS_LockoutDateTime TIMESTAMP ,
	GS_PasswordNeverChanges VARCHAR(10) ,
	GS_NextReviewDate TIMESTAMP ,
	GS_GB_HomeBranch CHAR(MAX) ,
	GS_GE_HomeDepartment CHAR(MAX) ,
	GS_GB_LastLogonBranch CHAR(MAX) ,
	GS_GE_LastLogonDepartment CHAR(MAX) ,
	GS_WorkingLanguage varchar(7)  ,
	GS_LastActivityDate TIMESTAMP ,
	GS_CommissionBasis varchar(3)  ,
	GS_NewClientCommissionRate decimal(8,1) ,
	GS_EstablishedClientCommissionRate decimal(8,1) ,
	GS_CommissionMinimumEarning DECIMAL(15,4) ,
	GS_IsActivityLogged VARCHAR(10) ,
	GS_ActiveDirectoryObjectGuid CHAR(MAX) ,
	GS_SystemCreateTimeUtc datetime ,
	GS_SystemCreateUser varchar(3)  ,
	GS_SystemLastEditTimeUtc datetime ,
	GS_SystemLastEditUser varchar(3)  ,
	GS_GC_PreferredPaymentCompany CHAR(MAX) ,
	GS_IsDevice VARCHAR(10) ,
	GS_IsTwoFactorAuthenticationEnabled VARCHAR(10) ,
	GS_PER CHAR(MAX) ,
	GS_RN_NKCountryCode varchar(2)  ,
	GS_CanLogin VARCHAR(10) ,
	GS_AddressMap varchar(50)  ,
	GS_GeoLocation GEOMETRY ,
	GS_ValidationStatus char(3)  ,
	GS_RN_NKNationalityCode varchar(2)  ,
	GS_DomainName nvarchar(255)  ,
	GS_IsDriver VARCHAR(10) ,
	GS_ActivityTrackingStatus varchar(3)  ,
	GS_PasswordHash VARCHAR(MAX)(20) ,
	GS_PasswordHashIterations int ,
	GS_PasswordSalt VARCHAR(MAX)(16)
)


CREATE TABLE OdysseyPTBPRD.JobBookedCtgMove (
	EW_PK CHAR(MAX) ,
	EW_DisplayOrder smallint ,
	EW_DropMode varchar(3)  ,
	EW_RequestedPickupTimeStart TIMESTAMP ,
	EW_RequestedPickupTimeEnd TIMESTAMP ,
	EW_E2PickupAddressID CHAR(MAX) ,
	EW_RequestedDeliveryTimeStart TIMESTAMP ,
	EW_RequestedDeliveryTimeEnd TIMESTAMP ,
	EW_E2WaitPointAddressID CHAR(MAX) ,
	EW_E2DeliveryAddressID CHAR(MAX) ,
	EW_JC_Container CHAR(MAX) ,
	EW_BookedPackCount int ,
	EW_F3_NKPackType varchar(3)  ,
	EW_BookedVolume decimal(9,3) ,
	EW_VolumeUQ varchar(2)  ,
	EW_BookedWeight decimal(9,3) ,
	EW_WeightUQ varchar(2)  ,
	EW_BookedHeight decimal(9,3) ,
	EW_BookedLength decimal(9,3) ,
	EW_BookedWidth decimal(9,3) ,
	EW_DimUnit varchar(2)  ,
	EW_Distance decimal(9,3) ,
	EW_DistanceUnit varchar(3)  ,
	EW_JJ CHAR(MAX) ,
	EW_IsValid VARCHAR(10)
)

CREATE TABLE OdysseyPTBPRD.JobCartage (
	JJ_PK CHAR(MAX) ,
	JJ_IsValid VARCHAR(10) ,
	JJ_IsCancelled VARCHAR(10) ,
	JJ_ShippingTransportMode varchar(3)  ,
	JJ_ContainerMode varchar(3)  ,
	JJ_Direction varchar(3)  ,
	JJ_Status varchar(3)  ,
	JJ_OH_ClientID CHAR(MAX) ,
	JJ_ConsignmentID varchar(35)  ,
	JJ_E3_NKJobType varchar(4)  ,
	JJ_DropMode varchar(3)  ,
	JJ_Weight decimal(9,3) ,
	JJ_WeightUQ varchar(2)  ,
	JJ_Volume decimal(9,3) ,
	JJ_VolumeUQ varchar(2)  ,
	JJ_OuterPacks int ,
	JJ_F3_NKPackType varchar(3)  ,
	JJ_OuterPacksType varchar(3)  ,
	JJ_WaybillNumber varchar(35)  ,
	JJ_GoodsDescription varchar(35)  ,
	JJ_OrderReferenceNumber varchar(35)  ,
	JJ_QuoteNumber varchar(25)  ,
	JJ_EstimatedPickup TIMESTAMP ,
	JJ_EstimatedDelivery TIMESTAMP ,
	JJ_A_JCL TIMESTAMP ,
	JJ_RS_NKServiceLevel varchar(3)  ,
	JJ_GB CHAR(MAX) ,
	JJ_JX_Sailing CHAR(MAX) ,
	JJ_ParentID CHAR(MAX) ,
	JJ_ParentTableCode varchar(3)  ,
	JJ_SystemLastEditTimeUtc TIMESTAMP ,
	JJ_SystemLastEditUser varchar(3)  ,
	JJ_SystemCreateTimeUtc TIMESTAMP ,
	JJ_SystemCreateUser varchar(3) 
)


CREATE TABLE OdysseyPTBPRD.JobChargeRevRecognition (
	D3_PK CHAR(MAX) ,
	D3_RecognitionType varchar(3)  ,
	D3_RecognitionDate TIMESTAMP ,
	D3_JH CHAR(MAX)
)

==========================================================================================================


CREATE TABLE OdysseyPTBPRD.JobConShipLink (
	JN_PK CHAR(MAX) ,
	JN_JK CHAR(MAX) ,
	JN_JS CHAR(MAX) 
)

CREATE TABLE OdysseyPTBPRD.JobConsol (
	JK_PK CHAR(MAX) ,
	JK_IsValid VARCHAR(10) ,
	JK_IsCancelled VARCHAR(10) ,
	JK_ConsolStatus varchar(3)  ,
	JK_Phase varchar(3)  ,
	JK_TransportMode char(3)  ,
	JK_ConsolMode char(3)  ,
	JK_AgentType char(3)  ,
	JK_AWBServiceLevel varchar(3)  ,
	JK_IsCFS VARCHAR(10) ,
	JK_IsForwarding VARCHAR(10) ,
	JK_IsNeutralMaster VARCHAR(10) ,
	JK_UniqueConsignRef varchar(20)  ,
	JK_MasterBillNum varchar(35)  ,
	JK_ShippedOnBoardDate TIMESTAMP ,
	JK_MasterBillIssueDate TIMESTAMP ,
	JK_BookingReference varchar(35)  ,
	JK_AgentsReference varchar(35)  ,
	JK_CustomsReference varchar(35)  ,
	JK_JK_MasterConsol CHAR(MAX) ,
	JK_PrepaidCollect char(3)  ,
	JK_OA_SendingForwarderAddress CHAR(MAX) ,
	JK_OA_CreditorAddress CHAR(MAX) ,
	JK_OA_ShippingLineAddress CHAR(MAX) ,
	JK_OA_ReceivingForwarderAddress CHAR(MAX) ,
	JK_DateLastForeignPort TIMESTAMP ,
	JK_DatePortOfFirstArrival TIMESTAMP ,
	JK_DateFirstForeignPort TIMESTAMP ,
	JK_OA_ArrivalUnpackCFSTransportAddress CHAR(MAX) ,
	JK_OA_ArrivalCTOAddress CHAR(MAX) ,
	JK_OA_UnpackDepotAddress CHAR(MAX) ,
	JK_OA_ContainerYardEmptyReturnAddress CHAR(MAX) ,
	JK_OA_DeparturePackCFSTransportAddress CHAR(MAX) ,
	JK_OA_ContainerYardEmptyPickupAddress CHAR(MAX) ,
	JK_OA_PackDepotAddress CHAR(MAX) ,
	JK_OA_DepartureCTOAddress CHAR(MAX) ,
	JK_RL_NKLoadPort varchar(5)  ,
	JK_RL_NKDischargePort varchar(5)  ,
	JK_RL_NKFirstForeignPort varchar(5)  ,
	JK_RL_NKLastForeignPort varchar(5)  ,
	JK_RL_NKPortOfFirstArrival varchar(5)  ,
	JK_NoOriginalBills VARCHAR(10) ,
	JK_NoCopyBills VARCHAR(10) ,
	JK_OverrideWaybillDefaults VARCHAR(10) ,
	JK_PrintOptionForColoadsOnManifest varchar(3)  ,
	JK_PrintOptionForColoadsOnOtherDocs varchar(3)  ,
	JK_PrintOptionForPackagesOnAWB varchar(3)  ,
	JK_CustomDate1 TIMESTAMP ,
	JK_CustomDate2 TIMESTAMP ,
	JK_CustomFlag1 VARCHAR(10) ,
	JK_CustomFlag2 VARCHAR(10) ,
	JK_ConsolCutOffDate TIMESTAMP ,
	JK_ConsolChargeable decimal(9,3) ,
	JK_ConsolChargeableRate DECIMAL(15,4) ,
	JK_OverrideConsolChargeable VARCHAR(10) ,
	JK_TotalShipmentChargableCheck decimal(9,3) ,
	JK_TotalShipmentChargeableUnit varchar(2)  ,
	JK_TotalShipmentActWeightCheck decimal(9,3) ,
	JK_TotalShipmentActVolumeCheck decimal(9,3) ,
	JK_TotalShipmentActOtherUnit char(2)  ,
	JK_TotalShipmentCountCheck smallint ,
	JK_CorrectedConsolWeight decimal(9,3) ,
	JK_CorrectedConsolWeightUnit varchar(2)  ,
	JK_CorrectedConsolVolume decimal(9,3) ,
	JK_CorrectedConsolVolumeUnit varchar(2)  ,
	JK_ReleaseType varchar(3)  ,
	JK_OH_DeparturePackCFSTransport CHAR(MAX) ,
	JK_OH_ArrivalUnpackCFSTransport CHAR(MAX) ,
	JK_OH_Creditor CHAR(MAX) ,
	JK_SystemCreateTimeUtc TIMESTAMP ,
	JK_SystemCreateUser varchar(3)  ,
	JK_SystemLastEditTimeUtc TIMESTAMP ,
	JK_SystemLastEditUser varchar(3)  ,
	JK_CoLoadBookingReference varchar(35)  ,
	JK_CoLoadMasterBill varchar(35)  ,
	JK_OA_CoLoadAddress CHAR(MAX) ,
	JK_RL_NKMasterBillIssuePlace varchar(5)  ,
	JK_ReceivingForwarderHandlingType varchar(3)  ,
	JK_SendingForwarderHandlingType varchar(3)  ,
	JK_ScreeningStatus char(3)  
)

CREATE TABLE OdysseyPTBPRD.JobConsolTransport (
	JW_PK CHAR(MAX) ,
	JW_IsValid VARCHAR(10) ,
	JW_TransportMode char(3)  ,
	JW_LegOrder VARCHAR(10) ,
	JW_TransportType char(3)  ,
	JW_RQ_TruckType CHAR(MAX) ,
	JW_Status varchar(3)  ,
	JW_PL_NKCarrierServiceLevel varchar(3)  ,
	JW_Vessel varchar(35)  ,
	JW_VoyageFlight varchar(10)  ,
	JW_IsLinked VARCHAR(10) ,
	JW_OA_DepartureLocation CHAR(MAX) ,
	JW_RL_NKLoadPort varchar(5)  ,
	JW_ETD TIMESTAMP ,
	JW_ATD TIMESTAMP ,
	JW_RL_NKDiscPort varchar(5)  ,
	JW_OA_ArrivalLocation CHAR(MAX) ,
	JW_ETA TIMESTAMP ,
	JW_ATA TIMESTAMP ,
	JW_OA_CarrierAddress CHAR(MAX) ,
	JW_CarrierBookingReference varchar(35)  ,
	JW_OA_CreditorAddress CHAR(MAX) ,
	JW_IsCharter VARCHAR(10) ,
	JW_Distance decimal(9,3) ,
	JW_DistanceUnit varchar(3)  ,
	JW_LegNotes varchar(MAX)  ,
	JW_CustomDecimal1 decimal(9,3) ,
	JW_CustomFlag1 VARCHAR(10) ,
	JW_CustomLink1 CHAR(MAX) ,
	JW_JX CHAR(MAX) ,
	JW_ParentType varchar(3)  ,
	JW_ParentGUID CHAR(MAX) ,
	JW_STA TIMESTAMP ,
	JW_STD TIMESTAMP ,
	JW_AircraftType varchar(3)  ,
	JW_OnlineScheduleStatus char(3)  ,
	JW_DepotAvailabilityDate TIMESTAMP ,
	JW_DepotCutOff TIMESTAMP ,
	JW_DepotReceivalCommences TIMESTAMP ,
	JW_DepotStorageDate TIMESTAMP ,
	JW_DocumentaryCutOff TIMESTAMP ,
	JW_TerminalAvailabilityDate TIMESTAMP ,
	JW_TerminalCutOff TIMESTAMP ,
	JW_TerminalReceivalCommences TIMESTAMP ,
	JW_TerminalStorageDate TIMESTAMP ,
	JW_VGMCutOff TIMESTAMP ,
	JW_VesselScreeningStatus char(3) 
)


CREATE TABLE OdysseyPTBPRD.JobContainer (
	JC_PK CHAR(MAX) ,
	JC_IsValid VARCHAR(10) ,
	JC_IsCFSRegistered VARCHAR(10) ,
	JC_IsEmptyContainer VARCHAR(10) ,
	JC_IsSealOk VARCHAR(10) ,
	JC_IsShipperOwned VARCHAR(10) ,
	JC_IsDamaged VARCHAR(10) ,
	JC_ContainerMode char(3)  ,
	JC_ContainerJobID varchar(20)  ,
	JC_ContainerStatus varchar(3)  ,
	JC_ContainerQuality varchar(3)  ,
	JC_RC CHAR(MAX) ,
	JC_ContainerNum varchar(20)  ,
	JC_SealNum varchar(20)  ,
	JC_AdditionalSealNum varchar(20)  ,
	JC_Additional2SealNum varchar(20)  ,
	JC_Description varchar(MAX)  ,
	JC_HarmonisedCode varchar(15)  ,
	JC_MarksAndNumbers varchar(MAX)  ,
	JC_F3_NKPackType varchar(3)  ,
	JC_ContainerImportDORelease varchar(15)  ,
	JC_ContainerCount smallint ,
	JC_ContainerStorageLocation varchar(10)  ,
	JC_StowagePosition varchar(25)  ,
	JC_FCLStorageModuleOnlyMaster varchar(20)  ,
	JC_Purpose char(3)  ,
	JC_UnpackGang varchar(10)  ,
	JC_UnpackShed varchar(10)  ,
	JC_DeliveryMode varchar(7)  ,
	JC_TrainWagonNumber varchar(10)  ,
	JC_OH_CFSClient CHAR(MAX) ,
	JC_ContainerRating varchar(6)  ,
	JC_OH_ShippingLine CHAR(MAX) ,
	JC_ExportDepotCustomsReference varchar(20)  ,
	JC_PackDate TIMESTAMP ,
	JC_ReleaseNum varchar(20)  ,
	JC_TempRecorderSerialNo varchar(20)  ,
	JC_DepartureSlotDateTime TIMESTAMP ,
	JC_DepartureSlotReference varchar(20)  ,
	JC_DepartureDockReceipt varchar(20)  ,
	JC_DepartureEstimatedPickup TIMESTAMP ,
	JC_OA_DepartureContainerYardAddress CHAR(MAX) ,
	JC_EmptyRequired TIMESTAMP ,
	JC_ContainerYardEmptyPickupGateOut TIMESTAMP ,
	JC_DepartureDeliveryByRail VARCHAR(10) ,
	JC_DepartureCartageAdvised TIMESTAMP ,
	JC_DepartureCartageRef varchar(20)  ,
	JC_DepartureCartageComplete TIMESTAMP ,
	JC_DepartureCartageDemurrageTime TIMESTAMP ,
	JC_DepartureCartageDemurrageCharge DECIMAL(15,4) ,
	JC_ArrivalSlotDateTime TIMESTAMP ,
	JC_ArrivalSlotReference varchar(20)  ,
	JC_ArrivalEstimatedDelivery TIMESTAMP ,
	JC_ArrivalDeliveryRequiredBy TIMESTAMP ,
	JC_OA_ArrivalContainerYardAddress CHAR(MAX) ,
	JC_ArrivalPickupByRail VARCHAR(10) ,
	JC_ArrivalCartageAdvised TIMESTAMP ,
	JC_ArrivalCartageRef varchar(20)  ,
	JC_ArrivalCartageComplete TIMESTAMP ,
	JC_ArrivalCartageDemurrageTime TIMESTAMP ,
	JC_ArrivalCartageDemurrageCharge DECIMAL(15,4) ,
	JC_FCLWharfGateIn TIMESTAMP ,
	JC_FCLOnBoardVessel TIMESTAMP ,
	JC_OverrideFCLAvailableStorage VARCHAR(10) ,
	JC_FCLUnloadFromVessel TIMESTAMP ,
	JC_FCLAvailable TIMESTAMP ,
	JC_FCLWharfGateOut TIMESTAMP ,
	JC_FCLStorageCommences TIMESTAMP ,
	JC_FCLHeldInTransitStaging VARCHAR(10) ,
	JC_FCLStorageDays VARCHAR(10) ,
	JC_FCLStorageCharge DECIMAL(15,4) ,
	JC_OverrideLCLAvailableStorage VARCHAR(10) ,
	JC_LCLUnpack TIMESTAMP ,
	JC_LCLAvailable TIMESTAMP ,
	JC_LCLStorageCommences TIMESTAMP ,
	JC_EmptyReadyForReturn TIMESTAMP ,
	JC_EmptyReturnedBy TIMESTAMP ,
	JC_ContainerYardEmptyReturnGateIn TIMESTAMP ,
	JC_ContainerDetentionDays VARCHAR(10) ,
	JC_ContainerDetentionCharge DECIMAL(15,4) ,
	JC_RH_NKContainerCommodityCode varchar(4)  ,
	JC_AirVentFlow decimal(8,1) ,
	JC_AirVentFlowRateUnit varchar(3)  ,
	JC_HumidityPercent VARCHAR(10) ,
	JC_IsControlledAtmosphere VARCHAR(10) ,
	JC_RefrigGeneratorID varchar(17)  ,
	JC_SetPointTemp decimal(8,3) ,
	JC_SetPointTempUnit varchar(1)  ,
	JC_TotalHeight decimal(9,3) ,
	JC_TotalLength decimal(9,3) ,
	JC_TotalWidth decimal(9,3) ,
	JC_TotalUnitOfMeasure varchar(2)  ,
	JC_OverhangBack decimal(9,3) ,
	JC_OverhangRight decimal(9,3) ,
	JC_DunnageWeight decimal(9,3) ,
	JC_GrossWeight decimal(9,3) ,
	JC_GrossWeightUQ varchar(2)  ,
	JC_TareWeight decimal(9,3) ,
	JC_GrossVolume decimal(9,3) ,
	JC_GrossVolumeUQ varchar(2)  ,
	JC_VolumeCapacity decimal(9,3) ,
	JC_VolumeCapacityUQ varchar(2)  ,
	JC_WeightCapacity decimal(9,3) ,
	JC_WeightCapacityUQ varchar(2)  ,
	JC_ContainerNotes varchar(MAX)  ,
	JC_FCLStorageArrivedUnderbond VARCHAR(10) ,
	JC_FCLStorageUnderbondCleared TIMESTAMP ,
	JC_DeliverySequence smallint ,
	JC_JX CHAR(MAX) ,
	JC_JK CHAR(MAX) ,
	JC_JS_FCLBookingOnlyLink CHAR(MAX) ,
	JC_VehicleMake varchar(35)  ,
	JC_VehicleModel varchar(35)  ,
	JC_VehicleYear smallint ,
	JC_VehicleColor varchar(35)  ,
	JC_VehicleNumberOfDoors VARCHAR(10) ,
	JC_VehicleTransmission varchar(3)  ,
	JC_GoodsValue DECIMAL(15,4) ,
	JC_RX_NKGoodsCurrency varchar(3)  ,
	JC_SystemCreateUser varchar(3)  ,
	JC_SystemCreateTimeUtc TIMESTAMP ,
	JC_SystemLastEditUser varchar(3)  ,
	JC_SystemLastEditTimeUtc TIMESTAMP ,
	JC_Additional2SealParty varchar(3)  ,
	JC_AdditionalSealParty varchar(3)  ,
	JC_CostSpotRate DECIMAL(15,4) ,
	JC_CostSpotRateMode varchar(3)  ,
	JC_GatewaySellSpotRate DECIMAL(15,4) ,
	JC_GatewaySellSpotRateMode varchar(3)  ,
	JC_GrossWeightVerificationDateTime TIMESTAMP ,
	JC_GrossWeightVerificationStatus char(10)  ,
	JC_GrossWeightVerificationType char(3)  ,
	JC_RX_NKCostSpotRateCurrency varchar(3)  ,
	JC_RX_NKGatewaySellSpotRateCurrency varchar(3)  ,
	JC_RX_NKSellSpotRateCurrency varchar(3)  ,
	JC_SealParty varchar(3)  ,
	JC_SellSpotRate DECIMAL(15,4) ,
	JC_SellSpotRateMode varchar(3)  ,
	JC_EmptyReturnReference varchar(20) 
)


CREATE TABLE OdysseyPTBPRD.JobContainerDetention (
	NC_PK CHAR(MAX) ,
	NC_DetentionType varchar(3)  ,
	NC_JobNumber varchar(20)  ,
	NC_GC CHAR(MAX) ,
	NC_OH_Principal CHAR(MAX) ,
	NC_OH_Client CHAR(MAX) ,
	NC_SystemCreateTimeUtc TIMESTAMP ,
	NC_SystemCreateUser varchar(3)  ,
	NC_SystemLastEditTimeUtc TIMESTAMP ,
	NC_SystemLastEditUser varchar(3)  
)

CREATE TABLE OdysseyPTBPRD.JobContainerPackPivot (
	J6_PK CHAR(MAX) ,
	J6_JC CHAR(MAX) ,
	J6_JL CHAR(MAX)
)

CREATE TABLE OdysseyPTBPRD.JobDocAddress (
	E2_PK CHAR(MAX) ,
	E2_IsValid VARCHAR(10) ,
	E2_AddressType varchar(3)  ,
	E2_IsResidential VARCHAR(10) ,
	E2_AddressSequence VARCHAR(10) ,
	E2_OA_Address CHAR(MAX) ,
	E2_Contact nvarchar(256)  ,
	E2_AddressOverride VARCHAR(10) ,
	E2_CompanyName nvarchar(100)  ,
	E2_Address1 nvarchar(50)  ,
	E2_Address2 nvarchar(50)  ,
	E2_City nvarchar(50)  ,
	E2_Postcode nvarchar(10)  ,
	E2_State nvarchar(25)  ,
	E2_RN_NKCountryCode varchar(2)  ,
	E2_Phone varchar(20)  ,
	E2_Mobile varchar(20)  ,
	E2_Fax varchar(20)  ,
	E2_GovRegNum nvarchar(35)  ,
	E2_GovRegNumType varchar(3)  ,
	E2_Email nvarchar(254)  ,
	E2_ParentID CHAR(MAX) ,
	E2_ParentTableCode varchar(3)  ,
	E2_ValidationStatus char(3)  ,
	E2_AddressMap varchar(50)  ,
	E2_ODP_NKDepartmentCode varchar(3)  ,
	E2_SuppressAddressValidationError VARCHAR(10) ,
	E2_SystemCreateTimeUtc TIMESTAMP ,
	E2_SystemCreateUser varchar(3)  ,
	E2_SystemLastEditTimeUtc TIMESTAMP ,
	E2_SystemLastEditUser varchar(3)  ,
	E2_GeoLocation GEOMETRY ,
	E2_AdditionalAddressInformation nvarchar(50)  ,
	E2_ScreeningStatus char(3)  
)

CREATE TABLE OdysseyPTBPRD.JobHeader (
	JH_PK CHAR(MAX) ,
	JH_IsValid VARCHAR(10) ,
	JH_HeaderType varchar(3)  ,
	JH_Name varchar(35)  ,
	JH_Description nvarchar(128)  ,
	JH_JobNum varchar(35)  ,
	JH_JobLocalReference varchar(20)  ,
	JH_ARInvoiceReference varchar(20)  ,
	JH_TH_NKQuoteNumber varchar(20)  ,
	JH_Status varchar(3)  ,
	JH_ProfitLossReasonCode varchar(3)  ,
	JH_A_JOP TIMESTAMP ,
	JH_RevenueRecognizedDate TIMESTAMP ,
	JH_A_JCL TIMESTAMP ,
	JH_JobPlannedStartDate TIMESTAMP ,
	JH_JobBufferPercentOverride VARCHAR(10) ,
	JH_IsProfitSharePosted VARCHAR(10) ,
	JH_LocalChargesCFX decimal(6,3) ,
	JH_OA_LocalChargesAddr CHAR(MAX) ,
	JH_OC_LocalBillingContact CHAR(MAX) ,
	JH_OA_AgentCollectAddr CHAR(MAX) ,
	JH_AgentChargesCFX decimal(6,3) ,
	JH_LocalClientInvoicingStyle varchar(3)  ,
	JH_SingleAgentsInvoicePerConsol VARCHAR(10) ,
	JH_UniqueJobInvoiceNumber smallint ,
	JH_PaymentCollectionStatus varchar(3)  ,
	JH_RatingHasBeenRun VARCHAR(10) ,
	JH_ExcludeFromPeriodicRating VARCHAR(10) ,
	JH_ProfitShareInvoice CHAR(MAX) ,
	JH_GB CHAR(MAX) ,
	JH_GE CHAR(MAX) ,
	JH_GC CHAR(MAX) ,
	JH_GS_NKRepSales varchar(3)  ,
	JH_GS_NKRepOps varchar(3)  ,
	JH_ParentID CHAR(MAX) ,
	JH_ParentTableCode varchar(3)  ,
	JH_JH_ParentJob CHAR(MAX) ,
	JH_SystemCreateTimeUtc TIMESTAMP ,
	JH_SystemCreateUser varchar(3)  ,
	JH_SystemLastEditTimeUtc TIMESTAMP ,
	JH_SystemLastEditUser varchar(3)  ,
	JH_HoldReason nvarchar(35)  
)

CREATE TABLE OdysseyPTBPRD.JobMawb (
	JM_PK CHAR(MAX) ,
	JM_IsValid VARCHAR(10) ,
	JM_Airline3DigitPrefix char(3)  ,
	JM_MAWB varchar(8)  ,
	JM_ServiceLevel char(3)  ,
	JM_IsPaper VARCHAR(10) ,
	JM_IsPrinted VARCHAR(10) ,
	JM_IsBorrowed VARCHAR(10) ,
	JM_OH_From CHAR(MAX) ,
	JM_OH_AllocatedTo CHAR(MAX) ,
	JM_ReservedUntil TIMESTAMP ,
	JM_RL_NKPortOfLoading varchar(5)  ,
	JM_IsCompletedAWBReturned VARCHAR(10) ,
	JM_IsBorrowedAWBInvoiced VARCHAR(10) ,
	JM_IsReportedToLender VARCHAR(10) ,
	JM_GB CHAR(MAX) ,
	JM_SystemCreateTimeUtc TIMESTAMP ,
	JM_SystemCreateUser varchar(3)  ,
	JM_ParentID CHAR(MAX) ,
	JM_ParentTableCode varchar(3)
)

CREATE TABLE OdysseyPTBPRD.JobPackLines (
	JL_PK CHAR(MAX) ,
	JL_IsValid VARCHAR(10) ,
	JL_FreightMode char(3)  ,
	JL_ItemNo smallint ,
	JL_EndItemNo smallint ,
	JL_PackageCount int ,
	JL_F3_NKPackType varchar(3)  ,
	JL_ContainerPackingOrder int ,
	JL_LinePrice DECIMAL(15,4) ,
	JL_Outturn int ,
	JL_OutturnedLength decimal(9,3) ,
	JL_OutturnedHeight decimal(9,3) ,
	JL_OutturnedWidth decimal(9,3) ,
	JL_OutturnedWeight decimal(9,3) ,
	JL_OutturnedVolume decimal(9,3) ,
	JL_OutturnComment varchar(250)  ,
	JL_Pillaged int ,
	JL_Damaged int ,
	JL_ActualWeight decimal(9,3) ,
	JL_ActualWeightUQ varchar(2)  ,
	JL_Length decimal(9,3) ,
	JL_Height decimal(9,3) ,
	JL_Width decimal(9,3) ,
	JL_UnitOfDimension varchar(2)  ,
	JL_ActualVolume decimal(9,3) ,
	JL_ActualVolumeUQ varchar(2)  ,
	JL_LoadingMeters decimal(9,3) ,
	JL_RefNumber varchar(20)  ,
	JL_Description varchar(65)  ,
	JL_DetailedDescription varchar(MAX)  ,
	JL_HarmonisedCode varchar(15)  ,
	JL_RN_NKOrigin varchar(2)  ,
	JL_RH_NKCommodityCode varchar(4)  ,
	JL_MarksAndNumbers varchar(MAX)  ,
	JL_JS CHAR(MAX) ,
	JL_CustomAttrib1 varchar(20)  ,
	JL_CustomAttrib2 varchar(20)  ,
	JL_CustomAttrib3 varchar(20)  ,
	JL_CustomAttrib4 varchar(20)  ,
	JL_CustomDecimal1 decimal(9,3) ,
	JL_CustomDecimal2 decimal(9,3) ,
	JL_CustomDate1 TIMESTAMP ,
	JL_CustomDate2 TIMESTAMP ,
	JL_CustomFlag1 VARCHAR(10) ,
	JL_CustomFlag2 VARCHAR(10) ,
	JL_ExportRefNumber varchar(35)  ,
	JL_ImportRefNumber varchar(35)  ,
	JL_VehicleColor varchar(35)  ,
	JL_VehicleMake varchar(35)  ,
	JL_VehicleModel varchar(35)  ,
	JL_VehicleNumberOfDoors VARCHAR(10) ,
	JL_VehicleTransmission varchar(3)  ,
	JL_VehicleYear smallint 
)


==========================================================================================================



CREATE TABLE OdysseyPTBPRD.JobSailing (
	JX_PK CHAR(MAX) ,
	JX_IsValid VARCHAR(10) ,
	JX_JA CHAR(MAX) ,
	JX_JB CHAR(MAX) ,
	JX_Status varchar(3)  ,
	JX_IsPublished VARCHAR(10) ,
	JX_DepotCutOff TIMESTAMP ,
	JX_DepotAvailabilityDate TIMESTAMP ,
	JX_DepotStorageDate TIMESTAMP ,
	JX_DepotReceivalCommences TIMESTAMP ,
	JX_ReservedMasterBill varchar(20)  ,
	JX_ContainerReleaseNumber varchar(20)  ,
	JX_UniqueReference varchar(20)  ,
	JX_OnlineScheduleStatus char(3)  ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)

CREATE TABLE OdysseyPTBPRD.JobShipment (
	JS_PK CHAR(MAX) ,
	JS_IsValid VARCHAR(10) ,
	JS_IsCancelled VARCHAR(10) ,
	JS_ShipmentStatus varchar(3)  ,
	JS_Phase varchar(3)  ,
	JS_UniqueConsignRef varchar(20)  ,
	JS_InterimReceipt varchar(35)  ,
	JS_CartageWaybill varchar(20)  ,
	JS_CFSReference varchar(20)  ,
	JS_AWBServiceLevel varchar(3)  ,
	JS_IsNeutralMaster VARCHAR(10) ,
	JS_ConsolReference varchar(20)  ,
	JS_HouseBill varchar(20)  ,
	JS_ShipmentType varchar(3)  ,
	JS_IsShipping VARCHAR(10) ,
	JS_IsDirectBooking VARCHAR(10) ,
	JS_IsCFSRegistered VARCHAR(10) ,
	JS_IsForwardRegistered VARCHAR(10) ,
	JS_IsBooking VARCHAR(10) ,
	JS_TranshipToOtherCFS VARCHAR(10) ,
	JS_BookingReference varchar(20)  ,
	JS_A_BKD TIMESTAMP ,
	JS_GoodsDescription varchar(35)  ,
	JS_GoodsValue DECIMAL(15,4) ,
	JS_RX_NKGoodsValueCurr varchar(3)  ,
	JS_InsuranceValue DECIMAL(15,4) ,
	JS_RX_NKInsuranceCurrency varchar(3)  ,
	JS_ShipperCODAmount DECIMAL(15,4) ,
	JS_ShipperCODPayMethod varchar(3)  ,
	JS_FreightSpotRateAutoratingMode varchar(3)  ,
	JS_FreightCostRate DECIMAL(15,4) ,
	JS_RX_NKFreightCostRateCurrency varchar(3)  ,
	JS_FreightCostRateAutoratingMode varchar(3)  ,
	JS_GatewayFreightSellRate DECIMAL(15,4) ,
	JS_RX_NKGatewayFreightSellRateCurrency varchar(3)  ,
	JS_FreightGatewaySellRateAutoratingMode varchar(3)  ,
	JS_PackingOrder int ,
	JS_ReleaseType char(3)  ,
	JS_OA_ExportReceivingDepot CHAR(MAX) ,
	JS_OA_ImportReleaseDepot CHAR(MAX) ,
	JS_OH_HandledOnBehalfOfForwarder CHAR(MAX) ,
	JS_OH_TranshipAgent CHAR(MAX) ,
	JS_OH_DeliveryAgent CHAR(MAX) ,
	JS_A_RCV TIMESTAMP ,
	JS_RL_NKOrigin varchar(5)  ,
	JS_E_DEP TIMESTAMP ,
	JS_RL_NKDestination varchar(5)  ,
	JS_E_ARV TIMESTAMP ,
	JS_ClientRequestedETA TIMESTAMP ,
	JS_RS_NKServiceLevel varchar(3)  ,
	JS_INCO char(3)  ,
	JS_AdditionalTerms varchar(50)  ,
	JS_JX CHAR(MAX) ,
	JS_OH_BookedShippingLine CHAR(MAX) ,
	JS_TransportMode char(3)  ,
	JS_PackingMode char(3)  ,
	JS_ActualVolume decimal(9,3) ,
	JS_DocumentedVolume decimal(9,3) ,
	JS_ManifestedVolume decimal(9,3) ,
	JS_UnitOfVolume varchar(2)  ,
	JS_ActualWeight decimal(9,3) ,
	JS_DocumentedWeight decimal(9,3) ,
	JS_ManifestedWeight decimal(9,3) ,
	JS_UnitOfWeight varchar(2)  ,
	JS_ActualChargeable decimal(9,3) ,
	JS_DocumentedChargeable decimal(9,3) ,
	JS_ManifestedChargeable decimal(9,3) ,
	JS_LoadingMeters decimal(9,3) ,
	JS_DocumentedLoadingMeters decimal(9,3) ,
	JS_ManifestedLoadingMeters decimal(9,3) ,
	JS_UnitFreightRate DECIMAL(15,4) ,
	JS_RX_NKFrtRateCurrency varchar(3)  ,
	JS_TotalPackageCount int ,
	JS_F3_NKTotalCountPackType varchar(3)  ,
	JS_OuterPacks int ,
	JS_F3_NKPackType varchar(3)  ,
	JS_NoOriginalBills VARCHAR(10) ,
	JS_NoCopyBills VARCHAR(10) ,
	JS_OverrideWaybillDefaults VARCHAR(10) ,
	JS_OH_ExportBroker CHAR(MAX) ,
	JS_HouseBillOfLadingType varchar(3)  ,
	JS_ShippedOnBoard varchar(3)  ,
	JS_ShippedOnBoardDate TIMESTAMP ,
	JS_HouseBillIssueDate TIMESTAMP ,
	JS_HBLAWBChargesDisplay varchar(3)  ,
	JS_HBLContainerPackModeOverride varchar(9)  ,
	JS_WarehouseLocation varchar(10)  ,
	JS_WL CHAR(MAX) ,
	JS_OH_ImportBroker CHAR(MAX) ,
	JS_VisibleTabs int ,
	JS_InvisibleTabsXML varchar(MAX)  ,
	JS_Legacy_Support_Columns_Start VARCHAR(10) ,
	JS_JS_ColoadMasterShipment CHAR(MAX) ,
	JS_JS_SplitSwitchShipment CHAR(MAX) ,
	JS_IsSplitShipment VARCHAR(10) ,
	JS_SystemLastEditTimeUtc TIMESTAMP ,
	JS_SystemLastEditUser varchar(3)  ,
	JS_SystemCreateTimeUtc TIMESTAMP ,
	JS_SystemCreateUser varchar(3)  ,
	JS_EFreightStatus varchar(3)  ,
	JS_RL_NKHouseBillIssuePlace varchar(5)  ,
	JS_RL_NKPlaceOfDischarge varchar(5)  ,
	JS_RL_NKPlaceOfReceipt varchar(5)  ,
	JS_AttachedOrderXMLUpdateCutOffDateUTC TIMESTAMP ,
	JS_TH_OneTimeQuote CHAR(MAX) ,
	JS_RL_NKDischargePort varchar(5)  ,
	JS_RL_NKFreightRateDestination varchar(5)  ,
	JS_RL_NKFreightRateOrigin varchar(5)  ,
	JS_RL_NKLoadPort varchar(5)  ,
	JS_ScreeningStatus char(3)  ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)

CREATE TABLE OdysseyPTBPRD.JobStorage (
	ET_PK CHAR(MAX) ,
	ET_StorageJobNumber varchar(20)  ,
	ET_StorageType varchar(3)  ,
	ET_BillingDate TIMESTAMP ,
	ET_StorageFromDate TIMESTAMP ,
	ET_StorageToDate TIMESTAMP ,
	ET_OH_Client CHAR(MAX) ,
	ET_WW CHAR(MAX)  ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)

CREATE TABLE OdysseyPTBPRD.JobSundryCharges (
	D4_PK CHAR(MAX) ,
	D4_SundriesJobType varchar(3)  ,
	D4_SundryJobMode varchar(3)  ,
	D4_SundryJobActivity varchar(3)  ,
	D4_JobNumber varchar(20)  ,
	D4_FromDate TIMESTAMP ,
	D4_ToDate TIMESTAMP ,
	D4_SundriesDescription varchar(80)  ,
	D4_AdditionalDetails varchar(256)  ,
	D4_OH_BillToParty CHAR(MAX) ,
	D4_GC CHAR(MAX)  ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)

CREATE TABLE OdysseyPTBPRD.JobVoyAccount (
	NA_PK CHAR(MAX) ,
	NA_JobNumber varchar(20)  ,
	NA_JV CHAR(MAX) ,
	NA_OH CHAR(MAX) ,
	NA_GC CHAR(MAX)  ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)

CREATE TABLE OdysseyPTBPRD.JobVoyage (
	JV_PK CHAR(MAX) ,
	JV_IsValid VARCHAR(10) ,
	JV_IsActive VARCHAR(10) ,
	JV_AirSeaRoad char(3)  ,
	JV_VoyageType varchar(3)  ,
	JV_VoyageFlight varchar(10)  ,
	JV_RV_NKVessel varchar(35)  ,
	JV_FlightDate TIMESTAMP ,
	JV_IsChartered VARCHAR(10) ,
	JV_IsCargoOnly VARCHAR(10) ,
	JV_RegistrationNo varchar(10)  ,
	JV_SendersMessageReference varchar(20)  ,
	JV_OH_Line CHAR(MAX) ,
	JV_AircraftType varchar(3)   ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)

CREATE TABLE OdysseyPTBPRD.JobVoyDestination (
	JB_PK CHAR(MAX) ,
	JB_IsValid VARCHAR(10) ,
	JB_RL_NKPortOfDischarge varchar(5)  ,
	JB_E_ARV TIMESTAMP ,
	JB_A_ARV TIMESTAMP ,
	JB_Berth varchar(10)  ,
	JB_ArrivalReference varchar(20)  ,
	JB_IsTranshipment VARCHAR(10) ,
	JB_AutoCreated VARCHAR(10) ,
	JB_JV CHAR(MAX) ,
	JB_OA_ArrivalCTOAddress CHAR(MAX) ,
	JB_SendersMessageReference varchar(20)  ,
	JB_AvailabilityDate TIMESTAMP ,
	JB_StorageDate TIMESTAMP ,
	JB_S_ARV TIMESTAMP  ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)

CREATE TABLE OdysseyPTBPRD.JobVoyOrigin (
	JA_PK CHAR(MAX) ,
	JA_IsValid VARCHAR(10) ,
	JA_E_DEP TIMESTAMP ,
	JA_A_DEP TIMESTAMP ,
	JA_E_ARV TIMESTAMP ,
	JA_A_ARV TIMESTAMP ,
	JA_RL_NKPortOfLoading varchar(5)  ,
	JA_Berth varchar(10)  ,
	JA_DepartReference varchar(20)  ,
	JA_AutoCreated VARCHAR(10) ,
	JA_JV CHAR(MAX) ,
	JA_OA_DepartureCTOAddress CHAR(MAX) ,
	JA_SendersMessageReference varchar(20)  ,
	JA_DocumentaryCutoff TIMESTAMP ,
	JA_CutOff TIMESTAMP ,
	JA_ReceivalCommences TIMESTAMP ,
	JA_DGCutOff TIMESTAMP ,
	JA_DGReceivalCommences TIMESTAMP ,
	JA_VGMCutOff TIMESTAMP ,
	JA_S_ARV TIMESTAMP ,
	JA_S_DEP TIMESTAMP  ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)


CREATE TABLE OdysseyPTBPRD.OrgAddress (
	OA_PK CHAR(MAX) ,
	OA_IsValid VARCHAR(10) ,
	OA_IsActive VARCHAR(10) ,
	OA_Code nvarchar(25)  ,
	OA_CompanyNameOverride nvarchar(100)  ,
	OA_Address1 nvarchar(50)  ,
	OA_Address2 nvarchar(50)  ,
	OA_City nvarchar(50)  ,
	OA_State nvarchar(25)  ,
	OA_PostCode nvarchar(10)  ,
	OA_RN_NKCountryCode varchar(2)  ,
	OA_ValidationStatus char(3)  ,
	OA_AddressMap varchar(50)  ,
	OA_Phone varchar(20)  ,
	OA_Fax varchar(20)  ,
	OA_Mobile varchar(20)  ,
	OA_Email nvarchar(254)  ,
	OA_UseCumulativeFreeWaitingTime VARCHAR(10) ,
	OA_PickupFromTimeOnly TIMESTAMP ,
	OA_PickupToTimeOnly TIMESTAMP ,
	OA_DeliverFromTimeOnly TIMESTAMP ,
	OA_DeliverToTimeOnly TIMESTAMP ,
	OA_DoNotAttendFrom TIMESTAMP ,
	OA_DoNotAttendTo TIMESTAMP ,
	OA_DockLeveler VARCHAR(10) ,
	OA_ForkLift VARCHAR(10) ,
	OA_PalletJack VARCHAR(10) ,
	OA_ContainerHandling varchar(3)  ,
	OA_AccessPoint varchar(3)  ,
	OA_LabourRequired varchar(3)  ,
	OA_CommunicationRequired varchar(3)  ,
	OA_Dock_Height varchar(3)  ,
	OA_FCLEquipmentNeeded varchar(3)  ,
	OA_LCLEquipmentNeeded varchar(3)  ,
	OA_AIREquipmentNeeded varchar(3)  ,
	OA_RL_NKRelatedPortCode varchar(5)  ,
	OA_OH CHAR(MAX) ,
	OA_DeliveryRoute varchar(3)  ,
	OA_DeliveryRouteSequence smallint ,
	OA_OtherWarehouseFacilities nvarchar(MAX)  ,
	OA_LoadingUnloadingConstraints nvarchar(MAX)  ,
	OA_AuthorityToLeave varchar(3)  ,
	OA_GroupNumber smallint ,
	OA_AdditionalAddressInformation nvarchar(50)  ,
	OA_GeofencePolygon geography ,
	OA_SuppressAddressValidationError VARCHAR(10) ,
	OA_VerifiesContainerGrossWeight VARCHAR(10) ,
	OA_SystemCreateTimeUtc TIMESTAMP ,
	OA_SystemCreateUser varchar(3)  ,
	OA_SystemLastEditTimeUtc TIMESTAMP ,
	OA_SystemLastEditUser varchar(3)  ,
	OA_Language varchar(7)  ,
	OA_GeoLocation geography ,
	OA_JobLoadingDuration int  ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)

CREATE TABLE OdysseyPTBPRD.OrgHeader (
	OH_PK CHAR(MAX) ,
	OH_IsValid VARCHAR(10) ,
	OH_Code nvarchar(12)  ,
	OH_IsActive VARCHAR(10) ,
	OH_FullName nvarchar(100)  ,
	OH_IsConsignee VARCHAR(10) ,
	OH_IsConsignor VARCHAR(10) ,
	OH_IsTransportClient VARCHAR(10) ,
	OH_IsWarehouseClient VARCHAR(10) ,
	OH_IsForwarder VARCHAR(10) ,
	OH_IsShippingProvider VARCHAR(10) ,
	OH_IsAirWholesaler VARCHAR(10) ,
	OH_IsSeaWholesaler VARCHAR(10) ,
	OH_IsRailProvider VARCHAR(10) ,
	OH_IsLineHaulProvider VARCHAR(10) ,
	OH_IsMiscFreightServices VARCHAR(10) ,
	OH_IsAirCTO VARCHAR(10) ,
	OH_IsAirLine VARCHAR(10) ,
	OH_IsBroker VARCHAR(10) ,
	OH_IsContainerYard VARCHAR(10) ,
	OH_IsLocalTransport VARCHAR(10) ,
	OH_IsPackDepot VARCHAR(10) ,
	OH_IsSeaCTO VARCHAR(10) ,
	OH_IsShippingLine VARCHAR(10) ,
	OH_IsUnpackDepot VARCHAR(10) ,
	OH_IsRailHead VARCHAR(10) ,
	OH_IsRoadFreightDepot VARCHAR(10) ,
	OH_IsShippingConsortium VARCHAR(10) ,
	OH_IsFumigationContractor VARCHAR(10) ,
	OH_IsGlobalAccount VARCHAR(10) ,
	OH_IsNationalAccount VARCHAR(10) ,
	OH_IsSalesLead VARCHAR(10) ,
	OH_IsCompetitor VARCHAR(10) ,
	OH_IsTempAccount VARCHAR(10) ,
	OH_IsPersonalEffectsAccount VARCHAR(10) ,
	OH_IsDistributionCentre VARCHAR(10) ,
	OH_IsUserFlag1 VARCHAR(10) ,
	OH_IsUserFlag2 VARCHAR(10) ,
	OH_IsUserFlag3 VARCHAR(10) ,
	OH_IsUserFlag4 VARCHAR(10) ,
	OH_IsUserFlag5 VARCHAR(10) ,
	OH_IsUserFlag6 VARCHAR(10) ,
	OH_IsUserFlag7 VARCHAR(10) ,
	OH_IsUserFlag8 VARCHAR(10) ,
	OH_IsUserFlag9 VARCHAR(10) ,
	OH_IsUserFlag10 VARCHAR(10) ,
	OH_IsUserFlag11 VARCHAR(10) ,
	OH_IsUserFlag12 VARCHAR(10) ,
	OH_IsUserFlag13 VARCHAR(10) ,
	OH_IsUserFlag14 VARCHAR(10) ,
	OH_IsUserFlag15 VARCHAR(10) ,
	OH_IsUserFlag16 VARCHAR(10) ,
	OH_IsUserFlag17 VARCHAR(10) ,
	OH_IsUserFlag18 VARCHAR(10) ,
	OH_IsUserFlag19 VARCHAR(10) ,
	OH_IsUserFlag20 VARCHAR(10) ,
	OH_IsUserFlag21 VARCHAR(10) ,
	OH_IsUserFlag22 VARCHAR(10) ,
	OH_IsUserFlag23 VARCHAR(10) ,
	OH_IsUserFlag24 VARCHAR(10) ,
	OH_RL_NKClosestPort varchar(5)  ,
	OH_Language varchar(7)  ,
	OH_SystemLastEditTimeUtc TIMESTAMP ,
	OH_SystemLastEditUser varchar(3)  ,
	OH_SystemCreateTimeUtc TIMESTAMP ,
	OH_SystemCreateUser varchar(3)  ,
	OH_IsControllingAgent VARCHAR(10) ,
	OH_IsControllingCustomer VARCHAR(10) ,
	OH_Category char(3)  ,
	OH_ScreeningStatus char(3)  ,
	OH_RSL_ShippingLine CHAR(MAX)  ,
	__ts_ms BIGINT DEFAULT ,
    __deleted varchar(20) DEFAULT 
)




























==================================================================================================



CREATE TABLE OdysseyPTBPRD.OrgMiscServ (
	OM_PK CHAR(MAX) ,
	OM_IsValid VARCHAR(10) ,
	OM_Airline3CharCode char(3) ,
	OM_IMEftCustomsFromImport VARCHAR(10) ,
	OM_IMEftQuarantineFromImport VARCHAR(10) ,
	OM_IMEftHoldUntilPayAuthorised VARCHAR(10) ,
	OM_IMEstDaysDeliveryAir int ,
	OM_IMEstDaysDeliveryFCL int ,
	OM_IMEstDaysDeliveryLCL int ,
	OM_IMMaxEFTAmount DECIMAL(15,4) ,
	OM_IMMinEFTAmount DECIMAL(15,4) ,
	OM_IMEFTBankAccount varchar(20) ,
	OM_IMEFTBankBSB varchar(15) ,
	OM_IMIsGSTDeferred VARCHAR(10) ,
	OM_IMMergeCustomsInvoiceLinesBy char(3) ,
	OM_IMOrderLineAttrib1 varchar(10) ,
	OM_IMOrderLineAttrib2 varchar(10) ,
	OM_IMOrderLineAttrib3 varchar(10) ,
	OM_IMOriginalSeaBills VARCHAR(10) ,
	OM_IMCopySeaBills VARCHAR(10) ,
	OM_IMSendImportDocsTo char(3) ,
	OM_IMSendSeaImportDocsTo varchar(3) ,
	OM_IMImporterCategory varchar(3) ,
	OM_IMAirDepotFreeDays VARCHAR(10) ,
	OM_IMSeaDepotFreeDays VARCHAR(10) ,
	OM_IMImporterOwnsPartNumbers VARCHAR(10) ,
	OM_IMOrderStatusCodePairList VARCHAR(MAX) ,
	OM_IMOrderLineStatusCodePairList VARCHAR(MAX) ,
	OM_IMLastOrderReference varchar(35) ,
	OM_IMDefaultToNewOrdersToNextOrderNum VARCHAR(10) ,
	OM_IMFCLEquipmentNeeded varchar(3) ,
	OM_IMLCLEquipmentNeeded varchar(3) ,
	OM_IMAirEquipmentNeeded varchar(3) ,
	OM_RS_NKIMDefaultServiceLevel varchar(3) ,
	OM_IMDefaultINCOTerm varchar(3) ,
	OM_IMAutoImpJobRefered VARCHAR(10) ,
	OM_IMAutoPopulateOwnerRefWithOrderNums varchar(3) ,
	OM_IMOwnsProducts VARCHAR(10) ,
	OM_IMPartAttrib1Type varchar(3) ,
	OM_IMPartAttrib1Name varchar(20) ,
	OM_IMPartAttrib1IsMandatory VARCHAR(10) ,
	OM_IMAttrib1IsKey VARCHAR(10) ,
	OM_IMPartAttrib2Type varchar(3) ,
	OM_IMPartAttrib2Name varchar(20) ,
	OM_IMPartAttrib2IsMandatory VARCHAR(10) ,
	OM_IMAttrib2IsKey VARCHAR(10) ,
	OM_IMPartAttrib3Type varchar(3) ,
	OM_IMPartAttrib3Name varchar(20) ,
	OM_IMPartAttrib3IsMandatory VARCHAR(10) ,
	OM_IMAttrib3IsKey VARCHAR(10) ,
	OM_IMUseExpiryDate VARCHAR(10) ,
	OM_IMUsePackingDate VARCHAR(10) ,
	OM_IMImporterRequiresOrderNumbersOnDocs VARCHAR(10) ,
	OM_IMJobRequireOrderTrackLink VARCHAR(10) ,
	OM_IMDocumentAddressPreference varchar(3) ,
	OM_IMDefaultWarehousePickOption varchar(3) ,
	OM_IMInvoiceDetailReportSort varchar(3) ,
	OM_IMInvoiceDetailReportSort2 varchar(3) ,
	OM_IMInvoiceDetailReportSort3 varchar(3) ,
	OM_IMShowDutyOnWarehouseEntries VARCHAR(10) ,
	OM_LandedCostMarginPercent1 decimal(8,2) ,
	OM_LandedCostMarginPercent2 decimal(8,2) ,
	OM_LandedCostMarginPercent3 decimal(8,2) ,
	OM_LastArchiveDate TIMESTAMP ,
	OM_EXJobRequireOrderTrackLink VARCHAR(10) ,
	OM_EXExporterRequiresOrderNumbersOnDocs VARCHAR(10) ,
	OM_RS_NKEXDefaultServiceLevel varchar(3) ,
	OM_EXGoodsDescription varchar(35) ,
	OM_EXExporterCategory varchar(3) ,
	OM_RX_NKEXDefCurrency varchar(3) ,
	OM_RN_NKEXDefaultCntryOfOrigin varchar(2) ,
	OM_EXFCLEquipmentNeeded varchar(3) ,
	OM_EXLCLEquipmentNeeded varchar(3) ,
	OM_EXAirEquipmentNeeded varchar(3) ,
	OM_EXAllowedToPrintOriginalBL VARCHAR(10) ,
	OM_EXDocumentAddressPreference varchar(3) ,
	OM_EXOwnsProducts VARCHAR(10) ,
	OM_OC_EXDefaultDGContact CHAR(MAX) ,
	OM_EXDefaultDGContactPhoneUsed varchar(3) ,
	OM_EXDefaultInvoicePriceFromProductLastCost varchar(3) ,
	OM_EXHandlingInstuctions varchar(200) ,
	OM_EXDefaultIncoTerm char(3) ,
	OM_EXMergeCustomsInvoiceLinesBy varchar(3) ,
	OM_EXPreAllocPrefix varchar(3) ,
	OM_FWAgentCategory varchar(3) ,
	OM_RX_NKFWDefCurrency varchar(3) ,
	OM_FWAgentBelongsToGroup VARCHAR(10) ,
	OM_FWHandlesAir VARCHAR(10) ,
	OM_FWHandlesSea VARCHAR(10) ,
	OM_FWHandlesSeaForPortOrCountry varchar(5) ,
	OM_FWHandlesAirForPortOrCountry varchar(5) ,
	OM_FWRequestForCreditAllowed VARCHAR(10) ,
	OM_FWBillCollectFeesOnSingleInvoice VARCHAR(10) ,
	OM_FWDealDirectlyWithUltimates VARCHAR(10) ,
	OM_FWIATACode varchar(14) ,
	OM_FWIATAAccountNumber varchar(14) ,
	OM_FWDirectAMSReporter VARCHAR(10) ,
	OM_CRCarrierCategory varchar(3) ,
	OM_CRVoyageRecyclingPeriodInMonths smallint ,
	OM_SVServicesCategory varchar(3) ,
	OM_CMSalesCategory varchar(3) ,
	OM_CMCompetitorActivity char(3) ,
	OM_CMLastCallDate TIMESTAMP ,
	OM_CMLastUnactionedCallDate TIMESTAMP ,
	OM_CMClientSize char(3) ,
	OM_CMNoOfEmployees int ,
	OM_CMEstimatedDateToClose TIMESTAMP ,
	OM_CMGrowthOutlook char(3) ,
	OM_CMFollowUpDate TIMESTAMP ,
	OM_CMLeadType varchar(5) ,
	OM_GS_NKCMLeadSourcePerson varchar(35) ,
	OM_CMDoesExports VARCHAR(10) ,
	OM_CMDoesImports VARCHAR(10) ,
	OM_RH_NKCMMainImportCmdty varchar(4) ,
	OM_RH_NKCMMainExportCmdty varchar(4) ,
	OM_CMUseTradeLaneFigures VARCHAR(10) ,
	OM_CMTotalClientRevenue DECIMAL(15,4) ,
	OM_CMPercentage decimal(9,3) ,
	OM_CMAcheivableClientRevenue DECIMAL(15,4) ,
	OM_CMEstimatedProfit DECIMAL(15,4) ,
	OM_CMWarehouseRevenue DECIMAL(15,4) ,
	OM_CMConsultingRevenue DECIMAL(15,4) ,
	OM_CMOverallClientRelation VARCHAR(10) ,
	OM_CMClientsDesireToRemain VARCHAR(10) ,
	OM_CMEaseClientCanBePoached VARCHAR(10) ,
	OM_CMAmountOfElectronicIntegration VARCHAR(10) ,
	OM_CMOverallEffectOfClientOnAirfreightCosts char(3) ,
	OM_CMOverallEffectOfClientOnLCLCosts char(3) ,
	OM_CMOverallEffectOfClientOnTEUCosts char(3) ,
	OM_CMOverallEffectOfClientOnWarehousingCosts char(3) ,
	OM_CMOverallEffectOfClientOnOtherCosts char(3) ,
	OM_CMAmountOfBusinessWon VARCHAR(10) ,
	OM_CMSalesTerritory varchar(3) ,
	OM_CMIsHouseAccount VARCHAR(10) ,
	OM_CMCommission char(3) ,
	OM_CMClientCommenced TIMESTAMP ,
	OM_CMClientPortalHomePage varchar(128) ,
	OM_CICompetitorCategory varchar(3) ,
	OM_CMDistanceCalculationProvider varchar(3) ,
	OM_CMDistanceCalculationVersion varchar(3) ,
	OM_CMDistanceCalculationMethod varchar(3) ,
	OM_CMPaidUpCapital DECIMAL(15,4) ,
	OM_CMEstablishedDate TIMESTAMP ,
	OM_CIEstimatedStaffThisLocation smallint ,
	OM_CITypeOfService char(3) ,
	OM_CIEstimatedStaffThisCountry smallint ,
	OM_CISellingStyle char(3) ,
	OM_CITurnover DECIMAL(15,4) ,
	OM_CIProfit DECIMAL(15,4) ,
	OM_CICapitalEmployed DECIMAL(15,4) ,
	OM_CICompetitiveRanking VARCHAR(10) ,
	OM_CIStrength varchar(MAX) ,
	OM_CIWeaknesses varchar(MAX) ,
	OM_CIOpportunities varchar(MAX) ,
	OM_CIThreats varchar(MAX) ,
	OM_GB_WhsDefaultWarehouse CHAR(MAX) ,
	OM_WhsOverrideSystemPickingRules VARCHAR(10) ,
	OM_WhsPickFromDefaultFIFO VARCHAR(10) ,
	OM_WhsPickFromFullPallets VARCHAR(10) ,
	OM_WhsPickFromConsolidatedFullPallets VARCHAR(10) ,
	OM_WhsPickFromPickFaces VARCHAR(10) ,
	OM_WhsPickFromPalletOverflow VARCHAR(10) ,
	OM_WhsPickFromBrokenPallets VARCHAR(10) ,
	OM_WhsPickFromFIFOBulkOnly VARCHAR(10) ,
	OM_WhsPickSortArrivalDate VARCHAR(10) ,
	OM_WhsPickSortExpiryDate VARCHAR(10) ,
	OM_WhsPickSortPackingDate VARCHAR(10) ,
	OM_WhsPickSortPickFace VARCHAR(10) ,
	OM_WhsPickSortLocationRow VARCHAR(10) ,
	OM_WhsPickSortLocationColumn VARCHAR(10) ,
	OM_WhsPickSortLocationLevel VARCHAR(10) ,
	OM_WhsExpiryNotificationFromDefaults VARCHAR(10) ,
	OM_WhsExpiryNotificationPeriod int ,
	OM_WhsClientInvoiceFormat varchar(3) ,
	OM_WhsOrderNumberUniquenessStrategy varchar(3) ,
	OM_SO_WhsPackingSlip CHAR(MAX) ,
	OM_WhsOverrideSystemPutawayRules VARCHAR(10) ,
	OM_IsAutoPackAllowed VARCHAR(10) ,
	OM_WhsPutawayToLocation VARCHAR(10) ,
	OM_WhsPutawayToPickFace VARCHAR(10) ,
	OM_WhsPutawayToProductArea VARCHAR(10) ,
	OM_WhsPutawayToClientArea VARCHAR(10) ,
	OM_WhsPutawaySortLocationColumn VARCHAR(10) ,
	OM_WhsPutawaySortLocationLevel VARCHAR(10) ,
	OM_WhsPutawaySortLocationRow VARCHAR(10) ,
	OM_WhsPutawaySameProductTogether VARCHAR(10) ,
	OM_WhsEDIChangeMessageCancelOrderLinesNotIncludedInMessage VARCHAR(10) ,
	OM_WhsGenerateBackOrdersOnShortfalls VARCHAR(10) ,
	OM_WhsAutoPckEdiOrders VARCHAR(10) ,
	OM_WhsOrderFulfillmentRule varchar(3) ,
	OM_WhsPackingSlipOrderBy varchar(3) ,
	OM_WhsOrderDefaultPickPriority VARCHAR(10) ,
	OM_WhsDefaultWarehousePickMode varchar(3) ,
	OM_WhsDefaultWarehouseRollUp VARCHAR(10) ,
	OM_WhsTransportPayer varchar(3) ,
	OM_MinimumShelfLifeAccepted smallint ,
	OM_WhsABCAnalysisEnabled VARCHAR(10) ,
	OM_WhsABCAnalysisMethod char(3) ,
	OM_WhsABCAnalysisPeriod char(3) ,
	OM_IsScanPackQtyAllowed VARCHAR(10) ,
	OM_IsLabelPrintedOnClosePackage VARCHAR(10) ,
	OM_CustomAttrib1 varchar(20) ,
	OM_CustomAttrib2 varchar(20) ,
	OM_CustomAttrib3 varchar(20) ,
	OM_CustomDate1 TIMESTAMP ,
	OM_CustomDate2 TIMESTAMP ,
	OM_CustomDate3 TIMESTAMP ,
	OM_CustomDecimal1 decimal(9,3) ,
	OM_CustomDecimal2 decimal(9,3) ,
	OM_CustomDecimal3 decimal(9,3) ,
	OM_CustomFlag1 VARCHAR(10) ,
	OM_CustomFlag2 VARCHAR(10) ,
	OM_CustomFlag3 VARCHAR(10) ,
	OM_CustomFlag4 VARCHAR(10) ,
	OM_OH CHAR(MAX) ,
	OM_GC_CMPreferredPaymentCompany CHAR(MAX) ,
	OM_CMAuthorityToLeave varchar(3) ,
	OM_CMIndustryVertical varchar(5) ,
	OM_CMPeriodOfActivity varchar(5) ,
	OM_ConsigneeAuthorityToLeave varchar(3) ,
	OM_ConsignorAuthorityToLeave varchar(3) ,
	OM_IMAllowOrders VARCHAR(10) ,
	OM_TBAllowMixedAccountNumbersOnManifest VARCHAR(10) ,
	OM_WCG_CartonGroup CHAR(MAX) ,
	OM_WhsIsRecalculateOrderPricing VARCHAR(10) ,
	OM_GG_OrgSecurityGroup CHAR(MAX) ,
	OM_IMAllowAttachedOrderXMLUpdate VARCHAR(10) ,
	OM_EXValidationForUnauditedClassification varchar(3) ,
	OM_IMValidationForUnauditedClassification varchar(3) ,
	OM_IMBalanceInvoicePackage VARCHAR(10) ,
	OM_WhsPackageToleranceEnabled VARCHAR(10) ,
	OM_WhsPackageWeightTolerancePercent decimal(4,1) ,
	OM_ARGlobalCreditApproved VARCHAR(10) ,
	OM_ARGlobalCreditLimit DECIMAL(15,4) ,
	OM_ARGlobalOnCreditHold VARCHAR(10) ,
	OM_OH_ARGlobalCreditGroup CHAR(MAX) ,
	OM_RX_NKARGlobalCreditCurrency varchar(3) ,
	OM_WhsEnforceScanOfProductsWhenPackingTote VARCHAR(10) ,
	OM_WhsPickFromHighPriorityLocations VARCHAR(10) 
)


CREATE TABLE OdysseyPTBPRD.OrgPartCategory (
	OPC_PK CHAR(MAX) ,
	OPC_CategoryCode varchar(8) ,
	OPC_CategoryDescription varchar(30) ,
	OPC_OPC_Parent CHAR(MAX) 
	__ts_ms BIGINT DEFAULT NULL,
    __deleted varchar(20) DEFAULT NULL
)

CREATE TABLE OdysseyPTBPRD.OrgPartRelation (
	OU_PK CHAR(MAX) ,
	OU_IsValid VARCHAR(10) ,
	OU_Relationship varchar(3) ,
	OU_LocalPartNumber varchar(35) ,
	OU_Ti smallint ,
	OU_Hi smallint ,
	OU_ClientUQ varchar(3) ,
	OU_ReleaseUQ varchar(3) ,
	OU_ReceiveUQ varchar(3) ,
	OU_RoyaltyPercent decimal(8,3) ,
	OU_RoyaltyFlatAmount DECIMAL(15,4) ,
	OU_RX_NKRoyaltyCurrency varchar(3) ,
	OU_LandedCostMarginPercent1 decimal(8,2) ,
	OU_LandedCostMarginPercent2 decimal(8,2) ,
	OU_LandedCostMarginPercent3 decimal(8,2) ,
	OU_FormLayoutController VARCHAR(10) ,
	OU_JulianBatchNoFormat varchar(6) ,
	OU_PickMode varchar(3) ,
	OU_UseExpiryDate VARCHAR(10) ,
	OU_UsePackingDate VARCHAR(10) ,
	OU_UsePartAttrib1 VARCHAR(10) ,
	OU_UsePartAttrib2 VARCHAR(10) ,
	OU_UsePartAttrib3 VARCHAR(10) ,
	OU_RFAttributeConfirm varchar(3) ,
	OU_ExpiryDateFormatString varchar(20) ,
	OU_PackingDateFormatString varchar(20) ,
	OU_CompletePalletPicking VARCHAR(10) ,
	OU_RollUpAttributesOnDocuments VARCHAR(10) ,
	OU_IsPartAttrib1ReleaseCaptured VARCHAR(10) ,
	OU_IsPartAttrib2ReleaseCaptured VARCHAR(10) ,
	OU_IsPartAttrib3ReleaseCaptured VARCHAR(10) ,
	OU_OH CHAR(MAX) ,
	OU_OP CHAR(MAX) ,
	OU_OPC_Category CHAR(MAX) ,
	OU_LocalPartDescription nvarchar(80) ,
	OU_WCG_CartonGroup CHAR(MAX) 
)

CREATE TABLE OdysseyPTBPRD.OrgPartUnit (
	OF_PK CHAR(MAX) ,
	OF_IsValid VARCHAR(10) ,
	OF_PackType varchar(3) ,
	OF_Weight decimal(9,3) ,
	OF_Height decimal(9,3) ,
	OF_Width decimal(9,3) ,
	OF_Depth decimal(9,3) ,
	OF_Cubic decimal(9,3) ,
	OF_ParentPackType varchar(3) ,
	OF_QuantityInParent decimal(18,6) ,
	OF_NoOfSKUsInThisPack decimal(9,3) ,
	OF_OP CHAR(MAX) 
)

CREATE TABLE OdysseyPTBPRD.OrgRelatedParty (
	PR_PK CHAR(MAX) ,
	PR_IsValid VARCHAR(10) ,
	PR_PartyType varchar(3) ,
	PR_FreightDirection varchar(3) ,
	PR_Service varchar(3) ,
	PR_Location varchar(5) ,
	PR_OA CHAR(MAX) ,
	PR_GC CHAR(MAX) ,
	PR_OH_Parent CHAR(MAX) ,
	PR_OH_RelatedParty CHAR(MAX) ,
	PR_SystemCreateTimeUtc TIMESTAMP ,
	PR_SystemCreateUser varchar(3) ,
	PR_SystemLastEditTimeUtc TIMESTAMP ,
	PR_SystemLastEditUser varchar(3) ,
	PR_CSAStatus varchar(3) ,
	PR_FreightTransportMode varchar(3) ,
	PR_FreightContainerMode varchar(3)
)

CREATE TABLE OdysseyPTBPRD.OrgSupplierPart (
	OP_PK CHAR(MAX) ,
	OP_IsValid VARCHAR(10) ,
	OP_IsActive VARCHAR(10) ,
	OP_IsWarehouseProduct VARCHAR(10) ,
	OP_PartNum varchar(35) ,
	OP_Desc nvarchar(80) ,
	OP_StockKeepingUnit varchar(3) ,
	OP_CountDecimalPlaces VARCHAR(10) ,
	OP_StockTakeCycle varchar(3) ,
	OP_RH_NKCommodityCode varchar(4) ,
	OP_IsResource VARCHAR(10) ,
	OP_Weight decimal(9,3) ,
	OP_NetWeight decimal(9,3) ,
	OP_WeightUQ varchar(2) ,
	OP_Cubic decimal(9,3) ,
	OP_CubicUQ varchar(2) ,
	OP_Depth decimal(9,3) ,
	OP_Height decimal(9,3) ,
	OP_Width decimal(9,3) ,
	OP_MeasureUQ varchar(2) ,
	OP_LastCost DECIMAL(15,4) ,
	OP_WeightedCost DECIMAL(15,4) ,
	OP_RX_NKLastWeightedCostCurr varchar(3) ,
	OP_QtyInStock decimal(9,2) ,
	OP_VendorPackQty decimal(9,3) ,
	OP_F3_NKPackType varchar(3) ,
	OP_VPReorderMinimum int ,
	OP_VPReorderMaximum int ,
	OP_OrderMultipleQty decimal(9,3) ,
	OP_OrderMultipleUnit varchar(3) ,
	OP_AutoPrintAssemblyInstructions VARCHAR(10) ,
	OP_CanDisassembleKit VARCHAR(10) ,
	OP_CanResell VARCHAR(10) ,
	OP_Division varchar(15) ,
	OP_Department varchar(15) ,
	OP_CustomDecimal1 decimal(9,3) ,
	OP_CustomDecimal2 decimal(9,3) ,
	OP_CustomDecimal3 decimal(9,3) ,
	OP_CustomDecimal4 decimal(9,3) ,
	OP_CustomDecimal5 decimal(9,3) ,
	OP_CustomAttrib1 varchar(25) ,
	OP_CustomAttrib2 varchar(25) ,
	OP_CustomAttrib3 varchar(25) ,
	OP_CustomAttrib4 varchar(25) ,
	OP_CustomAttrib5 varchar(25) ,
	OP_CustomFlag1 VARCHAR(10) ,
	OP_CustomFlag2 VARCHAR(10) ,
	OP_CustomFlag3 VARCHAR(10) ,
	OP_CustomFlag4 VARCHAR(10) ,
	OP_CustomFlag5 VARCHAR(10) ,
	OP_CustomDate1 TIMESTAMP ,
	OP_CustomDate2 TIMESTAMP ,
	OP_CustomDate3 TIMESTAMP ,
	OP_CustomDate4 TIMESTAMP ,
	OP_CustomDate5 TIMESTAMP ,
	OP_SystemCreateTimeUtc TIMESTAMP ,
	OP_SystemCreateUser varchar(3) ,
	OP_SystemLastEditTimeUtc TIMESTAMP ,
	OP_SystemLastEditUser varchar(3) ,
	OP_IsBarcoded VARCHAR(10) ,
	OP_IsComponentPickedOnSalesOrder VARCHAR(10) ,
	OP_KitIsAutoReplenished VARCHAR(10) ,
	OP_WSC_WhsProductStyleColour CHAR(MAX) ,
	OP_WSZ_WhsProductStyleSize CHAR(MAX) ,
	OP_Brand nvarchar(50) ,
	OP_Model nvarchar(50) 
) 

CREATE TABLE OdysseyPTBPRD.ProcessTasks (
	P9_PK CHAR(MAX) ,
	P9_IsValid VARCHAR(10) ,
	P9_IsPublished VARCHAR(10) ,
	P9_TaskID varchar(20) ,
	P9_Sequence int ,
	P9_Type varchar(3) ,
	P9_IsInterruptable VARCHAR(10) ,
	P9_Status varchar(3) ,
	P9_SE_NKMilestoneEvent varchar(3) ,
	P9_SE_NKTaskCompletionEvent varchar(3) ,
	P9_SE_NKExceptionEvent varchar(3) ,
	P9_EstimatedDefaultedFrom varchar(3) ,
	P9_EstimatedDefaultTimeDelta TIMESTAMP ,
	P9_EstimatedDefaultFromPredecessor int ,
	P9_ExceptionAddedUTC TIMESTAMP ,
	P9_IsCalendarItem VARCHAR(10) ,
	P9_ScheduledDateUTC TIMESTAMP ,
	P9_EstDuration TIMESTAMP ,
	P9_EstimateVariationFactor decimal(5,2) ,
	P9_EstimatedTimeToComplete TIMESTAMP ,
	P9_ActualDateUTC datetime ,
	P9_ActualDuration datetime ,
	P9_SuspendedAtUTC TIMESTAMP ,
	P9_CompletedTimeUtc TIMESTAMP ,
	P9_TotalSuspendedDuration TIMESTAMP ,
	P9_NonWorkHours TIMESTAMP ,
	P9_TaskCannotBeDeleted VARCHAR(10) ,
	P9_Notes VARCHAR(MAX) ,
	P9_CardNote nvarchar(40) ,
	P9_GS_NKAssignedStaffMember varchar(3) ,
	P9_GG_AssignedGroup CHAR(MAX) ,
	P9_Condition1 varchar(3) ,
	P9_AndOr varchar(3) ,
	P9_Condition2 varchar(3) ,
	P9_Condition2Value varchar(3) ,
	P9_LineTriggerType varchar(3) ,
	P9_TriggerCondition varchar(3) ,
	P9_RN_NKOriginCountry varchar(2) ,
	P9_RN_NKDestinationCountry varchar(2) ,
	P9_OA CHAR(MAX) ,
	P9_OC CHAR(MAX) ,
	P9_GC CHAR(MAX) ,
	P9_RespondToCascadedEvents VARCHAR(10) ,
	P9_TriggerField varchar(80) ,
	P9_ParentTemplateID CHAR(MAX) ,
	P9_ReferencedID CHAR(MAX) ,
	P9_ReferencedTableCode varchar(3) ,
	P9_ParentID CHAR(MAX) ,
	P9_ParentTableCode varchar(3) ,
	P9_SuspendedAt TIMESTAMP ,
	P9_ActualDate datetime ,
	P9_OriginalScheduledDateUtc TIMESTAMP ,
	P9_RecalculateScheduledDate VARCHAR(10) ,
	P9_ScheduledDate TIMESTAMP ,
	P9_MilestoneExceptionAdded TIMESTAMP ,
	P9_CascadedEventsContext varchar(250) ,
	P9_FH_ProcessHeader CHAR(MAX) ,
	P9_G4_RequiredCapability CHAR(MAX) ,
	P9_EstimatedHandoverTimeUtc TIMESTAMP ,
	P9_Description nvarchar(50) ,
	P9_TriggerFiredCountdown smallint ,
	P9_GB_TriggerBranch CHAR(MAX) ,
	P9_GB_TriggerDepartment CHAR(MAX) ,
	P9_PenetrationResetDateUtc datetime ,
	P9_TriggerContext char(3) 
)

CREATE TABLE OdysseyPTBPRD.RefCommodityCode (
	RH_PK CHAR(MAX) ,
	RH_Code varchar(4) ,
	RH_IsActive VARCHAR(10) ,
	RH_Description varchar(100) ,
	RH_IsTimber VARCHAR(10) ,
	RH_IsPerishable VARCHAR(10) ,
	RH_IsFlammable VARCHAR(10) ,
	RH_IsHazardous VARCHAR(10) ,
	RH_ExpiryDate TIMESTAMP ,
	RH_ReeferMinTemperature decimal(8,1) ,
	RH_ReeferMaxTemperature decimal(8,1) ,
	RH_ContainerVentRequired VARCHAR(10) ,
	RH_FN_NKNMFC varchar(15) ,
	RH_IsForwarding VARCHAR(10) ,
	RH_IsLandTransport VARCHAR(10) ,
	RH_IsPersonalEffects VARCHAR(10) ,
	RH_IsShipping VARCHAR(10) ,
	RH_IsSystem VARCHAR(10) ,
	RH_UniversalCommodityGroup varchar(10) 
)


CREATE TABLE OdysseyPTBPRD.RefContainer (
	RC_PK CHAR(MAX) ,
	RC_Code varchar(10) ,
	RC_IsActive VARCHAR(10) ,
	RC_ShippingMode varchar(3) ,
	RC_Description varchar(35) ,
	RC_Length decimal(9,3) ,
	RC_Height decimal(9,3) ,
	RC_Width decimal(9,3) ,
	RC_ContainerType varchar(3) ,
	RC_IsHighCube VARCHAR(10) ,
	RC_HasTynes VARCHAR(10) ,
	RC_HasVents VARCHAR(10) ,
	RC_IsIso VARCHAR(10) ,
	RC_ISOType char(4) ,
	RC_TareWeight decimal(9,3) ,
	RC_GrossWeight decimal(9,3) ,
	RC_CubicCapacity decimal(9,3) ,
	RC_StorageClass varchar(3) ,
	RC_HandlingRateClass varchar(4) ,
	RC_FreightRateClass varchar(4) ,
	RC_IATARateClass varchar(3) ,
	RC_USContainerCode varchar(2) ,
	RC_TEU decimal(5,2) ,
	RC_ISOEquipmentSizeTypeCode varchar(10) 
)

CREATE TABLE OdysseyPTBPRD.RefCurrency (
	RX_PK CHAR(MAX) ,
	RX_Code char(3) ,
	RX_IsActive VARCHAR(10) ,
	RX_IsSystem VARCHAR(10) ,
	RX_Symbol nvarchar(3) ,
	RX_Desc nvarchar(35) ,
	RX_UnitName varchar(20) ,
	RX_SubUnitName varchar(20) ,
	RX_SubUnitRatio int 




=================================================================================================



CREATE TABLE OdysseyPTBPRD.StmALog (
	SL_PK CHAR(MAX) ,
	SL_Table varchar(35)  ,
	SL_Parent CHAR(MAX) ,
	SL_IsEstimate char(1)  ,
	SL_IsCancelled char(1)  ,
	SL_Reference varchar(1024)  ,
	SL_PostedTimeUtc datetime ,
	SL_EventTime datetime ,
	SL_GS_NKUser char(3)  ,
	SL_SE_NKEvent char(3)  ,
	SL_FireWorkflow VARCHAR(10) ,
	SL_GB_NKBranch varchar(3)  ,
	SL_GE_NKDepartment varchar(3)  
)

CREATE TABLE OdysseyPTBPRD.StmNote (
	ST_PK CHAR(MAX) ,
	ST_ParentID CHAR(MAX) ,
	ST_Table varchar(35)  ,
	ST_GC_RelatedCompany CHAR(MAX) ,
	ST_IsCustomDescription VARCHAR(10) ,
	ST_ForceRead VARCHAR(10) ,
	ST_NoteData VARCHAR(MAX) ,
	ST_NoteText nvarchar(MAX)  ,
	ST_NoteType char(3)  ,
	ST_NoteContext varchar(3)  ,
	ST_Description nvarchar(50) 
)

CREATE TABLE OdysseyPTBPRD.WhsDocket (
	WD_PK CHAR(MAX) ,
	WD_OH_Client CHAR(MAX) ,
	WD_OH_Forwarder CHAR(MAX) ,
	WD_DocketID varchar(15)  ,
	WD_ExternalReferenceSplit VARCHAR(10) ,
	WD_DocketType varchar(3)  ,
	WD_DocketSubType varchar(3)  ,
	WD_PickOption varchar(3)  ,
	WD_ExternalReference varchar(35)  ,
	WD_CustomerReference varchar(35)  ,
	WD_GoodsDescription nvarchar(35)  ,
	WD_TransportMode varchar(3)  ,
	WD_ContainerMode varchar(3)  ,
	WD_TotalOrderValue DECIMAL(15,4) ,
	WD_RX_NKTotalOrderCurrency varchar(3)  ,
	WD_ExWhsJobGuid CHAR(MAX) ,
	WD_TotalUnits decimal(18,3) ,
	WD_F3_NKTotalPackType varchar(3)  ,
	WD_TotalWeight decimal(9,3) ,
	WD_TotalWeightUnit varchar(2)  ,
	WD_TotalCubic decimal(9,3) ,
	WD_TotalCubicUnit varchar(2)  ,
	WD_TotalPallets smallint ,
	WD_WeightVolSetFromImport VARCHAR(10) ,
	WD_BookingDate TIMESTAMP ,
	WD_ArrivalDate TIMESTAMP ,
	WD_FinalisedDate datetime ,
	WD_RequiredDate TIMESTAMP ,
	WD_DocketStatus varchar(3)  ,
	WD_PackagesSent int ,
	WD_PalletsSent smallint ,
	WD_UnitsSent decimal(18,3) ,
	WD_WeightSentUserEntered decimal(9,3) ,
	WD_WeightSent decimal(9,3) ,
	WD_CubicSent decimal(9,3) ,
	WD_ETA TIMESTAMP ,
	WD_ETD TIMESTAMP ,
	WD_TransportReference varchar(35)  ,
	WD_LocalCartInsuranceCost DECIMAL(15,4) ,
	WD_DropMode varchar(3)  ,
	WD_INCO varchar(3)  ,
	WD_ShipperCODAmount DECIMAL(15,4) ,
	WD_CODPayMethod varchar(3)  ,
	WD_WhsOrderFulfillmentRule varchar(3)  ,
	WD_AddPalletWeightToOrder VARCHAR(10) ,
	WD_PL_NKCarrierServiceLevel varchar(3)  ,
	WD_RS_NKServiceLevel varchar(3)  ,
	WD_AutoFinaliseBOMIntoInventory VARCHAR(10) ,
	WD_CustomAttrib1 varchar(15)  ,
	WD_CustomAttrib2 varchar(15)  ,
	WD_CustomAttrib3 varchar(15)  ,
	WD_CustomAttrib4 varchar(35)  ,
	WD_CustomAttrib5 varchar(35)  ,
	WD_CustomDate1 TIMESTAMP ,
	WD_CustomDate2 TIMESTAMP ,
	WD_CustomDecimal1 decimal(9,3) ,
	WD_CustomDecimal2 decimal(9,3) ,
	WD_CustomDecimal3 decimal(9,3) ,
	WD_CustomDecimal4 decimal(9,3) ,
	WD_CustomDecimal5 decimal(9,3) ,
	WD_CustomFlag1 VARCHAR(10) ,
	WD_CustomFlag2 VARCHAR(10) ,
	WD_CustomFlag3 VARCHAR(10) ,
	WD_CustomFlag4 VARCHAR(10) ,
	WD_CustomFlag5 VARCHAR(10) ,
	WD_WD_ParentDocket CHAR(MAX) ,
	WD_WD_Split CHAR(MAX) ,
	WD_WP CHAR(MAX) ,
	WD_WW_Whs CHAR(MAX) ,
	WD_SystemCreateTimeUtc TIMESTAMP ,
	WD_SystemCreateUser varchar(3)  ,
	WD_SystemLastEditTimeUtc TIMESTAMP ,
	WD_SystemLastEditUser varchar(3)  ,
	WD_PickPriority VARCHAR(10) ,
	WD_IsPutawayTransfer VARCHAR(10) ,
	WD_QualityAuditRequired VARCHAR(10) ,
	WD_WL_CrossDock CHAR(MAX) ,
	WD_WP_ParentPickForTransfer CHAR(MAX) ,
	WD_PackingAfterPickingRequired VARCHAR(10) ,
	WD_IsAuthorisedToLeave VARCHAR(10) ,
	WD_StartedReceiving VARCHAR(10) 
)

CREATE TABLE OdysseyPTBPRD.WhsDocketLine (
	WE_PK CHAR(MAX) ,
	WE_IsValid VARCHAR(10) ,
	WE_LineNo smallint ,
	WE_SubLineNo smallint ,
	WE_OP CHAR(MAX) ,
	WE_F3_NKPackType varchar(3)  ,
	WE_ClientOrderedUnits decimal(18,3) ,
	WE_TransactionQuantity decimal(18,3) ,
	WE_PackageGroupId varchar(15)  ,
	WE_PerPackageQty decimal(18,3) ,
	WE_ExpiryDate date ,
	WE_PartAttrib1 varchar(25)  ,
	WE_PartAttrib2 varchar(25)  ,
	WE_PartAttrib3 varchar(25)  ,
	WE_BondedEntryKey varchar(35)  ,
	WE_PackingDate date ,
	WE_AdjustmentArrivalDate TIMESTAMP ,
	WE_RecommendedUnitPrice DECIMAL(15,4) ,
	WE_RX_NKUnitPriceCurrency varchar(3)  ,
	WE_UnitDiscountPercent decimal(4,2) ,
	WE_UnitDiscountAmount DECIMAL(15,4) ,
	WE_UnitPriceAfterDiscount DECIMAL(15,4) ,
	WE_ExtendedLinePrice DECIMAL(15,4) ,
	WE_DocketLineStatus varchar(3)  ,
	WE_FinalisedDate datetime ,
	WE_PalletID varchar(25)  ,
	WE_ReceiveCrossDockOrderNo varchar(35)  ,
	WE_RequiredByDate TIMESTAMP ,
	WE_WL_TransferFrom CHAR(MAX) ,
	WE_TransferFromPalletId varchar(25)  ,
	WE_WE_OriginalDocketLineForRating CHAR(MAX) ,
	WE_WE_MatchingLine CHAR(MAX) ,
	WE_LineComment varchar(250)  ,
	WE_IsOriginalInventory VARCHAR(10) ,
	WE_ReasonCode varchar(3)  ,
	WE_CustomAttrib1 varchar(15)  ,
	WE_CustomAttrib2 varchar(15)  ,
	WE_CustomAttrib3 varchar(15)  ,
	WE_CustomAttrib4 varchar(15)  ,
	WE_CustomAttrib5 varchar(15)  ,
	WE_CustomAttrib6 varchar(80)  ,
	WE_CustomTextBlob1 varchar(MAX)  ,
	WE_CustomFlag1 VARCHAR(10) ,
	WE_CustomFlag2 VARCHAR(10) ,
	WE_CustomFlag3 VARCHAR(10) ,
	WE_CustomFlag4 VARCHAR(10) ,
	WE_CustomFlag5 VARCHAR(10) ,
	WE_CustomDate1 TIMESTAMP ,
	WE_CustomDate2 TIMESTAMP ,
	WE_CustomDate3 TIMESTAMP ,
	WE_CustomDate4 TIMESTAMP ,
	WE_CustomDate5 TIMESTAMP ,
	WE_CustomDecimal1 decimal(9,3) ,
	WE_CustomDecimal2 decimal(9,3) ,
	WE_CustomDecimal3 decimal(9,3) ,
	WE_CustomDecimal4 decimal(9,3) ,
	WE_CustomDecimal5 decimal(9,3) ,
	WE_WL CHAR(MAX) ,
	WE_WD CHAR(MAX) ,
	WE_WE_ParentDocketLine CHAR(MAX) ,
	WE_PickGroup smallint ,
	WE_GS_NKPutawayBy varchar(3)  ,
	WE_PutawayTime datetime ,
	WE_StockOnHand decimal(18,3) ,
	WE_WHC_NKOriginalInventoryHeldCode varchar(8)  ,
	WE_WHC_NKCurrentInventoryHeldCode varchar(8)  ,
	WE_CurrentInventoryStatus varchar(3)  ,
	WE_OriginalInventoryStatus varchar(3)  ,
	WE_DocketLineType char(3)  ,
	WE_UnloadedTime TIMESTAMPTZ 
)


==========================================================================================================


CREATE TABLE OdysseyPTBPRD.WhsDocketReference (
	WX_PK CHAR(MAX) ,
	WX_RefType varchar(3)  ,
	WX_Reference varchar(25)  ,
	WX_WD CHAR(MAX) 
)

CREATE TABLE OdysseyPTBPRD.WhsLocation (
	WL_PK CHAR(MAX) ,
	WL_IsValid VARCHAR(10) ,
	WL_WA_PickingArea CHAR(MAX) ,
	WL_WR CHAR(MAX) ,
	WL_Column smallint ,
	WL_Level smallint ,
	WL_Tray smallint ,
	WL_LocationStatus varchar(3)  ,
	WL_PickMethod varchar(3)  ,
	WL_MaxWeight decimal(9,3) ,
	WL_MaxWeightUnit varchar(2)  ,
	WL_MaxCubic decimal(9,3) ,
	WL_MaxCubicUnit varchar(2)  ,
	WL_Width decimal(9,3) ,
	WL_Height decimal(9,3) ,
	WL_Depth decimal(9,3) ,
	WL_ApprovedKnownLocation varchar(3)  ,
	WL_MaximumPickCountBeforeAutomatedStocktake int ,
	WL_FinalisedPickCount int ,
	WL_PickPathSequence int ,
	WL_MaxQuantity decimal(18,3) ,
	WL_MaxQuantityUnit varchar(3)  ,
	WL_WLT_LocationType CHAR(MAX) ,
	WL_RS_NKTransitServiceLevel varchar(3)  ,
	WL_TransitDischargeLRC varchar(5)  ,
	WL_WA_PutawayArea CHAR(MAX) ,
	WL_CycleCountPathSequence int ,
	WL_SystemCreateTimeUtc TIMESTAMP ,
	WL_SystemCreateUser varchar(3)  ,
	WL_SystemLastEditTimeUtc TIMESTAMP ,
	WL_SystemLastEditUser varchar(3)  ,
	WL_LastAllocatedOrChangedDate TIMESTAMP ,
	WL_PutawayPathSequence int ,
	WL_CycleCountLastPerformed TIMESTAMPTZ ,
	WL_LastInventoryChangeDate TIMESTAMPTZ 
)

CREATE TABLE OdysseyPTBPRD.WhsPick (
	WP_PK CHAR(MAX) ,
	WP_PickNo varchar(15)  ,
	WP_PickStatus varchar(3)  ,
	WP_PickOption varchar(3)  ,
	WP_PercentageComplete VARCHAR(10) ,
	WP_WW_Whs CHAR(MAX) ,
	WP_CartoniseSplitCases VARCHAR(10) ,
	WP_IsCartonised VARCHAR(10) ,
	WP_PickCasesByLabel VARCHAR(10) ,
	WP_PickPalletsByLabel VARCHAR(10) ,
	WP_WL_DockDoor CHAR(MAX) ,
	WP_SystemCreateTimeUtc TIMESTAMP ,
	WP_SystemCreateUser varchar(3)  ,
	WP_SystemLastEditTimeUtc TIMESTAMP ,
	WP_SystemLastEditUser varchar(3)  ,
	WP_ForcePickByCaseUOMTypeAllocation VARCHAR(10) 
)

CREATE TABLE OdysseyPTBPRD.WhsPickLine (
	WZ_PK CHAR(MAX) ,
	WZ_Units decimal(18,3) ,
	WZ_GS_NKAssignedTo varchar(3)  ,
	WZ_PickedDateTime datetime ,
	WZ_WE_TransactionLine CHAR(MAX) ,
	WZ_WE_InventoryLine CHAR(MAX) ,
	WZ_VerifiedEmpty char(1)  ,
	WZ_OriginalReservedQty decimal(18,3) ,
	WZ_F3_NKAllocatedPackType varchar(3)  ,
	WZ_IsPicking VARCHAR(10) ,
	WZ_WE_OriginalPickedInventoryLine CHAR(MAX) 
)

CREATE TABLE OdysseyPTBPRD.WhsProductStyle (
	WST_PK CHAR(MAX) ,
	WST_Code varchar(20)  ,
	WST_Description varchar(128)  ,
	WST_OH_Owner CHAR(MAX) )
) 

CREATE TABLE OdysseyPTBPRD.WhsProductStyleColour (
	WSC_PK CHAR(MAX) ,
	WSC_WST_ProductStyle CHAR(MAX) ,
	WSC_Code varchar(3)  ,
	WSC_Description varchar(128) 
)

CREATE TABLE OdysseyPTBPRD.WhsReleaseCapturedAttributes (
	WRA_PK CHAR(MAX) ,
	WRA_PartAttrib1 varchar(25)  ,
	WRA_PartAttrib2 varchar(25)  ,
	WRA_PartAttrib3 varchar(25)  ,
	WRA_Units decimal(18,3) ,
	WRA_WZ_PickLine CHAR(MAX)
)

CREATE TABLE OdysseyPTBPRD.WhsRow (
	WR_PK CHAR(MAX) ,
	WR_Name varchar(25)  ,
	WR_Columns smallint ,
	WR_Levels smallint ,
	WR_Trays smallint ,
	WR_WW_Whs CHAR(MAX) ,
	WR_PickPathSequence smallint ,
	WR_SystemLastEditTimeUtc TIMESTAMP ,
	WR_SystemLastEditUser varchar(3)  ,
	WR_SystemCreateTimeUtc TIMESTAMP ,
	WR_SystemCreateUser varchar(3) 
)

CREATE TABLE OdysseyPTBPRD.WhsWarehouse (
	WW_PK CHAR(MAX) ,
	WW_IsActive VARCHAR(10) ,
	WW_WarehouseCode varchar(3)  ,
	WW_IsVirtualWarehouse VARCHAR(10) ,
	WW_IsBondedWarehouse VARCHAR(10) ,
	WW_WarehouseName varchar(50)  ,
	WW_LocationColumnsAlpha VARCHAR(10) ,
	WW_LocationLevelsAlpha VARCHAR(10) ,
	WW_LocationTraysAlpha VARCHAR(10) ,
	WW_LocationComponentDelimiter varchar(1)  ,
	WW_AutoPrintPickingSlip VARCHAR(10) ,
	WW_AutoPrintPackingSlip VARCHAR(10) ,
	WW_LocationsHaveLeadingZeros VARCHAR(10) ,
	WW_UseArrivalDateForInwardsFinalisedDate VARCHAR(10) ,
	WW_UseRequiredDateForOutwardsFinalisedDate VARCHAR(10) ,
	WW_AutoPrintPickingShortfallItems VARCHAR(10) ,
	WW_AutoPrintPickingNonPickedItems VARCHAR(10) ,
	WW_AutoPrintOrderSummaryOnPick VARCHAR(10) ,
	WW_AutoPrintOrderCopyForMOPOnPick VARCHAR(10) ,
	WW_LocationColumnsZeroBased VARCHAR(10) ,
	WW_LocationLevelsZeroBased VARCHAR(10) ,
	WW_LocationTraysZeroBased VARCHAR(10) ,
	WW_TransitSecurityProcessingRequired VARCHAR(10) ,
	WW_GB_RelatedCompanyBranch CHAR(MAX) ,
	WW_OA_WarehouseAddress CHAR(MAX) ,
	WW_UseGS1PrefixFallback VARCHAR(10) ,
	WW_ABCAnalysisEnabled VARCHAR(10) ,
	WW_VerifyEmptyLocations VARCHAR(10) ,
	WW_WarehouseType char(3)  ,
	WW_DefaultOutboundDockDoor CHAR(MAX) ,
	WW_DGContactPhoneType varchar(3)  ,
	WW_IsPickByUOMEnabled VARCHAR(10) ,
	WW_OC_DGContact CHAR(MAX) ,
	WW_WLT_DefaultLocationType CHAR(MAX) ,
	WW_FTZDetailedTrackingMethod char(3)  ,
	WW_FTZDetailedTrackingWarningPercentage smallint ,
	WW_FTZIsDetailedTrackingEnabled VARCHAR(10) ,
	WW_NumberOfCycleCountLocationsToAutoAssign VARCHAR(10) ,
	WW_ScanAll VARCHAR(10) ,
	WW_DefaultInboundDockDoor CHAR(MAX) 
)



CREATE TABLE OdysseyPTBPRD.vw_JobDocAddress (
	E2_PK CHAR(MAX) ,
	E2_ParentID CHAR(MAX),
	E2_ParentTableCode varchar(50)  ,
	E2_AddressType varchar(50),
	E2_AddressOverride varchar(10),
	E2_AddressSequence smallint,
	OA_PK CHAR(MAX),
	OH_PK CHAR(MAX),
	OA_Code nvarchar(200),
	OH_Code	nvarchar(100),
	CompanyName	nvarchar(500),
	Address1 nvarchar(100),
	Address2 nvarchar(100),
	PostCode nvarchar(100),
	City nvarchar(100),
	State nvarchar(50),
	CountryCode	varchar(50)
)

=============================================================================================



CREATE TABLE OdysseyPTBPRD.vw_Report_ProductInfo(
    OP_PK	char(MAX),
    OP_PartNum	varchar(50),
    OP_StockKeepingUnit	varchar(50),
    OP_CountDecimalPlaces	smallint,
    OP_StockTakeCycle	varchar(50),
    OP_RH_NKCommodityCode	varchar(50),
    OP_Weight	decimal(9,3),
    OP_WeightUQ	varchar(50),
    OP_Cubic	decimal(9,3),
    OP_CubicUQ	varchar(50),
    OP_Depth	decimal(9,3),
    OP_Height	decimal(9,3),
    OP_Width	decimal(9,3),
    OP_MeasureUQ	varchar(50),
    OP_LastCost	DECIMAL(15,4),
    OP_WeightedCost	DECIMAL(15,4),
    OP_QtyInStock	decimal(9,3),
    OP_VendorPackQty	decimal(9,3),
    OP_VPReorderMinimum	int,
    OP_VPReorderMaximum	int,
    OP_OrderMultipleQty	decimal(9,3),
    OP_OrderMultipleUnit	varchar(50),
    OP_Division	varchar(50),
    OP_Department	varchar(50),
    OP_CustomDecimal1	decimal(9,3),
    OP_CustomDecimal2	decimal(9,3),
    OP_CustomDecimal3	decimal(9,3),
    OP_CustomDecimal4	decimal(9,3),
    OP_CustomDecimal5	decimal(9,3),
    OP_CustomAttrib1	varchar(50),
    OP_CustomAttrib2	varchar(50),
    OP_CustomAttrib3	varchar(50),
    OP_CustomAttrib4	varchar(50),
    OP_CustomAttrib5	varchar(50),
    OP_CustomDate1	TIMESTAMP,
    OP_CustomDate2	TIMESTAMP,
    OP_CustomDate3	TIMESTAMP,
    OP_CustomDate4	TIMESTAMP,
    OP_CustomDate5	TIMESTAMP,
    OP_NetWeight	decimal(9,3),
    OP_Brand	nvarchar(50),
    OP_Model	nvarchar(50),
    OP_RX_NKLastWeightedCostCurr	varchar(50),
    OP_F3_NKPackType	varchar(50),
    OP_SystemCreateTimeUtc	TIMESTAMP,
    OP_SystemCreateUser	varchar(50),
    OP_SystemLastEditTimeUtc	TIMESTAMP,
    OP_SystemLastEditUser	varchar(50),
    OP_IsActive	varchar(10),
    OP_IsResource	varchar(10),
    OP_CustomFlag1	varchar(10),
    OP_CustomFlag2	varchar(10),
    OP_CustomFlag3	varchar(10),
    OP_CustomFlag4	varchar(10),
    OP_CustomFlag5	varchar(10),
    OP_IsWarehouseProduct	varchar(10),
    OP_IsValid	varchar(10),
    OP_AutoPrintAssemblyInstructions	varchar(10),
    OP_CanDisassembleKit	varchar(10),
    OP_CanResell	varchar(10),
    OP_Desc	nvarchar(50),
    OP_IsComponentPickedOnSalesOrder	varchar(10),
    OP_IsBarcoded	varchar(10),
    UnitsPerPallet	decimal(9,3)
)

CREATE TABLE OdysseyPTBPRD.WhsDocketCustomAttributes(
DocketPK	char(MAX),
WhsDocket_CustomAttrib1	varchar(50),
WhsDocket_CustomAttrib2	varchar(50),
WhsDocket_CustomAttrib3	varchar(50),
WhsDocket_CustomAttrib4	varchar(50),
WhsDocket_CustomAttrib5	varchar(50),
WhsDocket_CustomDate1	TIMESTAMP,
WhsDocket_CustomDate2	TIMESTAMP,
WhsDocket_CustomDecimal1	decimal(9,3),
WhsDocket_CustomDecimal2	decimal(9,3),
WhsDocket_CustomDecimal3	decimal(9,3),
WhsDocket_CustomDecimal4	decimal(9,3),
WhsDocket_CustomDecimal5	decimal(9,3),
WhsDocket_CustomFlag1	varchar(10),
WhsDocket_CustomFlag2	varchar(10),
WhsDocket_CustomFlag3	varchar(10),
WhsDocket_CustomFlag4	varchar(10),
WhsDocket_CustomFlag5	varchar(10)
)

CREATE TABLE OdysseyPTBPRD.WhsLocationView(
WLV_PK	char(MAX),
WLV_IsValid	VARCHAR(10),
WLV_WA_PickingArea	char(MAX),
WLV_WA_PutawayArea	char(MAX),
WLV_WR	char(MAX),
WLV_Column	smallint,
WLV_Level	smallint,
WLV_Tray	smallint,
WLV_WLT_LocationType	char(MAX),
WLV_LocationStatus	varchar(50),
WLV_PickMethod	varchar(50),
WLV_MaxWeight	decimal(9,3),
WLV_MaxWeightUnit	varchar(50),
WLV_MaxCubic	decimal(9,3),
WLV_MaxCubicUnit	varchar(50),
WLV_Width	decimal(9,3),
WLV_Height	decimal(9,3),
WLV_Depth	decimal(9,3),
WLV_ApprovedKnownLocation	varchar(50),
WLV_MaximumPickCountBeforeAutomatedStocktake	int,
WLV_PickPathSequence	int,
WLV_MaxQuantity	decimal(9,3),
WLV_MaxQuantityUnit	varchar(50),
WLV_WW_Whs	char(MAX),
WLV_RowName	varchar(50),
WLV_TransitDischargeLRC	varchar(50),
WLV_RS_NKTransitServiceLevel	varchar(50),
WLV_TransitDischargeAndServiceLevelFakeColumnForUX	varchar(50),
WLV_FormattedColumn	varchar(50),
WLV_FormattedLevel	varchar(50),
WLV_FormattedTray	varchar(50),
WLV_LocationString	varchar(50),
WLV_CycleCountPathSequence	int,
WLV_PutawayPathSequence	int,
WLV_FinalisedPickCount	int,
WLV_LastInventoryChangeDate	datetimeoffset,
WLV_CycleCountLastPerformed	datetimeoffset,
WLV_LastAllocatedOrChangedDate	TIMESTAMP,
WLV_SystemCreateTimeUtc	TIMESTAMP,
WLV_SystemCreateUser	varchar(50),
WLV_SystemLastEditTimeUtc	TIMESTAMP,
WLV_SystemLastEditUser	varchar(50),
)



CREATE TABLE OdysseyPTBPRD.WhsDocketLineCustomAttributes(
DocketLinePK	char(MAX),
WhsDocketLine_CustomAttrib1	varchar(500),
WhsDocketLine_CustomAttrib2	varchar(500),
WhsDocketLine_CustomAttrib3	varchar(500),
WhsDocketLine_CustomAttrib4	varchar(500),
WhsDocketLine_CustomAttrib5	varchar(500),
WhsDocketLine_CustomAttrib6	varchar(500),
WhsDocketLine_CustomDate1	TIMESTAMP,
WhsDocketLine_CustomDate2	TIMESTAMP,
WhsDocketLine_CustomDate3	TIMESTAMP,
WhsDocketLine_CustomDate4	TIMESTAMP,
WhsDocketLine_CustomDate5	TIMESTAMP,
WhsDocketLine_CustomDecimal1	decimal(9,3),
WhsDocketLine_CustomDecimal2	decimal(9,3),
WhsDocketLine_CustomDecimal3	decimal(9,3),
WhsDocketLine_CustomDecimal4	decimal(9,3),
WhsDocketLine_CustomDecimal5	decimal(9,3),
WhsDocketLine_CustomFlag1	varchar(10),
WhsDocketLine_CustomFlag2	varchar(10),
WhsDocketLine_CustomFlag3	varchar(10),
WhsDocketLine_CustomFlag4	varchar(10),
WhsDocketLine_CustomFlag5	varchar(10),
WhsDocketLine_CustomTextBlob	varchar(MAX)
)